import { NextRequest } from "next/server";
import { randomUUID } from "crypto";
import { apiError, apiSuccess } from "@/lib/api/response";
import { requireAdmin } from "@/lib/auth/admin";
import { logError } from "@/lib/observability/logger";
import {
  IMAGE_SEARCH_VERSION,
  isAutoGeneratedImageUrl,
  populateItineraryImages,
} from "@/lib/image-search";
import type { Json } from "@/lib/database.types";
import { resolveSharePaymentContext } from "@/lib/share/admin-share";
import { normalizeSharePaymentConfig } from "@/lib/share/payment-config";
import {
  maybeAttachSharedItineraryPaymentConfig,
  withOptionalSharedItineraryPaymentConfig,
} from "@/lib/share/payment-config-compat";

/**
 * POST /api/admin/share/create
 *
 * Creates (or returns existing) share link for an itinerary.
 * Optionally auto-saves an unsaved itinerary first.
 *
 * Body:
 *   - itineraryId?: string          — existing itinerary ID
 *   - rawItineraryData?: object     — if no itineraryId, auto-save this itinerary first
 *   - templateId?: string           — share template (default: "safari_story")
 *
 * Returns: { shareCode, shareUrl, itineraryId }
 */
export async function POST(request: NextRequest) {
  const auth = await requireAdmin(request, { requireOrganization: true });
  if (!auth.ok) return auth.response;

  const { userId, organizationId, adminClient } = auth;

  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return apiError("Invalid JSON body", 400);
  }

  let itineraryId = typeof body.itineraryId === "string" ? body.itineraryId : null;
  const rawItineraryData = body.rawItineraryData as Record<string, unknown> | undefined;
  const templateId =
    typeof body.templateId === "string" ? body.templateId : "safari_story";
  const paymentConfig =
    Object.prototype.hasOwnProperty.call(body, "paymentConfig")
      ? normalizeSharePaymentConfig(body.paymentConfig ?? null)
      : undefined;

  // Auto-save unsaved itinerary if needed
  if (!itineraryId && rawItineraryData) {
    const { data: saved, error: saveErr } = await adminClient
      .from("itineraries")
      .insert({
        user_id: userId,
        trip_title: typeof rawItineraryData.trip_title === "string"
          ? rawItineraryData.trip_title
          : "Untitled Trip",
        destination: typeof rawItineraryData.destination === "string"
          ? rawItineraryData.destination
          : "Unknown",
        summary: typeof rawItineraryData.summary === "string"
          ? rawItineraryData.summary
          : null,
        duration_days: typeof rawItineraryData.duration_days === "number"
          ? rawItineraryData.duration_days
          : null,
        raw_data: rawItineraryData as unknown as Json,
      })
      .select("id")
      .single();

    if (saveErr || !saved) {
      logError("Failed to auto-save itinerary for share", saveErr);
      return apiError("Failed to save itinerary", 500);
    }

    itineraryId = saved.id;

    // Also create a trip record so it appears on the Trips page
    try {
      await adminClient.from("trips").insert({
        itinerary_id: itineraryId,
        client_id: userId,
        organization_id: organizationId,
        status: "draft",
        destination: typeof rawItineraryData.destination === "string"
          ? rawItineraryData.destination
          : null,
      });
    } catch (tripErr) {
      // Non-critical: trip creation can fail gracefully
      logError("Trip record creation failed during share", tripErr);
    }
  }

  if (!itineraryId) {
    return apiError("Either itineraryId or rawItineraryData is required", 400);
  }

  // Verify the itinerary belongs to this user/org
  const { data: itinerary } = await adminClient
    .from("itineraries")
    .select("id, user_id, raw_data, destination")
    .eq("id", itineraryId)
    .maybeSingle();

  if (!itinerary) {
    return apiError("Itinerary not found", 404);
  }

  // Backfill images for any activities missing them (not just when zero have images)
  const rawData = itinerary.raw_data as {
    image_search_version?: number;
    destination?: string;
    days?: Array<{ activities?: Array<{ image?: string; imageUrl?: string; title: string; location?: string }> }>;
  } | null;
  if (rawData?.days) {
    const currentImageSearchVersion =
      typeof rawData.image_search_version === "number" ? rawData.image_search_version : 0;
    const needsImages = rawData.days.some((day) =>
      (day.activities ?? []).some((a) => !a.image && !a.imageUrl)
    );
    const shouldRefreshAutoGeneratedImages =
      currentImageSearchVersion < IMAGE_SEARCH_VERSION &&
      rawData.days.some((day) =>
        (day.activities ?? []).some((a) => isAutoGeneratedImageUrl(a.image || a.imageUrl))
      );

    if (needsImages || shouldRefreshAutoGeneratedImages) {
      try {
        const withImages = await populateItineraryImages(
          {
            destination: rawData.destination ?? itinerary.destination ?? "travel",
            image_search_version: currentImageSearchVersion,
            days: rawData.days.map((d) => ({
              ...d,
              activities: (d.activities ?? []).map((a) => ({ ...a, title: a.title ?? "Activity" })),
            })),
          },
          { refreshAutoGenerated: shouldRefreshAutoGeneratedImages }
        );
        const updatedRawData = { ...rawData, ...withImages, days: withImages.days };
        await adminClient
          .from("itineraries")
          .update({ raw_data: updatedRawData as unknown as Json })
          .eq("id", itineraryId);
      } catch (imgErr) {
        logError("Image backfill failed during share creation", imgErr);
      }
    }
  }

  const paymentContext = await resolveSharePaymentContext({
    adminClient,
    itineraryId,
  });

  // Check for existing share link
  const { data: existing, paymentConfigSupported } = await withOptionalSharedItineraryPaymentConfig<
    { id: string; share_code: string; payment_config?: Json | null } | { id: string; share_code: string } | null
  >(
    async () =>
      adminClient
        .from("shared_itineraries")
        .select("id, share_code, payment_config")
        .eq("itinerary_id", itineraryId)
        .maybeSingle(),
    async () =>
      adminClient
        .from("shared_itineraries")
        .select("id, share_code")
        .eq("itinerary_id", itineraryId)
        .maybeSingle(),
  );

  if (existing?.share_code) {
    const updates: Record<string, unknown> = { template_id: templateId };
    if (paymentConfig !== undefined && paymentConfigSupported) {
      updates.payment_config = (paymentConfig || null) as unknown as Json;
    }

    await adminClient
      .from("shared_itineraries")
      .update(updates)
      .eq("id", existing.id);

    return apiSuccess({
      shareCode: existing.share_code,
      shareUrl: `https://tripbuilt.com/share/${existing.share_code}`,
      itineraryId,
      paymentEligible: paymentContext.paymentEligible,
      paymentDisabledReason: paymentContext.paymentDisabledReason,
      paymentDefaults: paymentContext.paymentDefaults,
      paymentConfig: paymentConfig === undefined ? paymentContext.existingPaymentConfig : paymentConfig,
    });
  }

  // Create new share link
  const shareCode = randomUUID().replace(/-/g, "").slice(0, 16);
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  const { error: insertError } = await adminClient
    .from("shared_itineraries")
    .insert(maybeAttachSharedItineraryPaymentConfig({
      itinerary_id: itineraryId,
      share_code: shareCode,
      status: "active",
      template_id: templateId,
      expires_at: expiresAt.toISOString(),
    }, paymentConfigSupported, (paymentConfig || null) as unknown as Json));

  if (insertError) {
    logError("Failed to create share link", insertError);
    return apiError("Failed to create share link", 500);
  }

  return apiSuccess({
    shareCode,
    shareUrl: `https://tripbuilt.com/share/${shareCode}`,
    itineraryId,
    paymentEligible: paymentContext.paymentEligible,
    paymentDisabledReason: paymentContext.paymentDisabledReason,
    paymentDefaults: paymentContext.paymentDefaults,
    paymentConfig: paymentConfig === undefined ? paymentContext.existingPaymentConfig : paymentConfig,
  });
}
