import { StyleSheet } from '@react-pdf/renderer';

export const safariStyles = StyleSheet.create({
  coverPage: {
    position: 'relative',
    backgroundColor: '#111827',
    color: '#ffffff',
  },
  coverImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  coverOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  coverContent: {
    position: 'absolute',
    top: 46,
    left: 42,
    right: 42,
  },
  coverBrandRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  coverCompany: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.5,
  },
  coverLogo: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#ffffff',
  },
  coverKicker: {
    fontSize: 14,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  coverTitle: {
    fontSize: 48,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 8,
    lineHeight: 1.1,
  },
  coverDestination: {
    fontSize: 22,
    marginBottom: 8,
  },
  coverSummary: {
    fontSize: 12,
    lineHeight: 1.5,
    maxWidth: 420,
  },
  coverBottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 40,
    paddingRight: 40,
    backgroundColor: '#111827',
  },
  coverBottomCell: {
    flex: 1,
  },
  coverBottomLabel: {
    fontSize: 10,
    color: '#d1d5db',
    textTransform: 'uppercase',
    marginBottom: 2,
    letterSpacing: 1,
  },
  coverBottomValue: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
  },
  page: {
    backgroundColor: '#f3f4f6',
    paddingTop: 38,
    paddingBottom: 34,
    paddingLeft: 32,
    paddingRight: 32,
  },
  storyCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 22,
    marginBottom: 18,
  },
  pageTitle: {
    fontSize: 30,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 10,
    color: '#111827',
  },
  pageSubtitle: {
    fontSize: 12,
    color: '#4b5563',
    lineHeight: 1.6,
    marginBottom: 10,
  },
  highlightsRow: {
    flexDirection: 'row',
    marginTop: 8,
  },
  highlightCard: {
    flex: 1,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    padding: 12,
    marginRight: 10,
    minHeight: 80,
  },
  highlightCardLast: {
    marginRight: 0,
  },
  highlightLabel: {
    fontSize: 10,
    textTransform: 'uppercase',
    color: '#6b7280',
    marginBottom: 4,
  },
  highlightValue: {
    fontSize: 14,
    color: '#111827',
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  highlightText: {
    fontSize: 10,
    color: '#4b5563',
    lineHeight: 1.4,
  },
  daysPageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  daysHeaderTitle: {
    fontSize: 24,
    fontFamily: 'Helvetica-Bold',
    color: '#111827',
    marginLeft: 12,
  },
  daysHeaderPill: {
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 14,
  },
  daysHeaderPillText: {
    color: '#ffffff',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: 'Helvetica-Bold',
  },
  dayBlock: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  dayTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  dayImage: {
    width: 140,
    height: 96,
    borderRadius: 8,
    marginRight: 12,
  },
  dayHeadingWrap: {
    flex: 1,
  },
  dayKicker: {
    fontSize: 10,
    textTransform: 'uppercase',
    color: '#6b7280',
    marginBottom: 2,
  },
  dayContinuation: {
    fontSize: 8,
    color: '#9ca3af',
    textTransform: 'uppercase',
    marginBottom: 2,
    letterSpacing: 0.8,
  },
  dayTitle: {
    fontSize: 19,
    fontFamily: 'Helvetica-Bold',
    color: '#111827',
    marginBottom: 4,
  },
  activityList: {
    marginTop: 10,
  },
  activityRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  activityIndex: {
    width: 16,
    fontSize: 10,
    color: '#6b7280',
  },
  activityTextWrap: {
    flex: 1,
  },
  activityTitle: {
    fontSize: 11,
    color: '#111827',
    fontFamily: 'Helvetica-Bold',
    marginBottom: 1,
  },
  activityMeta: {
    fontSize: 9,
    color: '#6b7280',
    lineHeight: 1.3,
  },
  closingCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 24,
    marginTop: 10,
  },
  closingTitle: {
    fontSize: 28,
    fontFamily: 'Helvetica-Bold',
    color: '#111827',
    marginBottom: 12,
  },
  closingBody: {
    fontSize: 12,
    color: '#4b5563',
    lineHeight: 1.7,
    marginBottom: 16,
  },
  closingContact: {
    fontSize: 12,
    color: '#111827',
    marginBottom: 6,
  },
  closingAccentLine: {
    height: 3,
    width: 120,
    borderRadius: 999,
    marginBottom: 14,
  },
});
