import { StyleSheet } from '@react-pdf/renderer';

export const urbanStyles = StyleSheet.create({
  page: {
    backgroundColor: '#f8fafc',
    paddingTop: 26,
    paddingBottom: 30,
    paddingLeft: 30,
    paddingRight: 30,
  },
  masthead: {
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    paddingBottom: 10,
    marginBottom: 14,
  },
  mastheadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  company: {
    fontSize: 12,
    color: '#111827',
    fontFamily: 'Helvetica-Bold',
  },
  contacts: {
    fontSize: 9,
    color: '#374151',
    textAlign: 'right',
    lineHeight: 1.4,
  },
  logo: {
    width: 54,
    height: 54,
    borderRadius: 8,
    marginLeft: 10,
  },
  heroCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 12,
    marginBottom: 14,
  },
  heroImage: {
    width: '100%',
    height: 220,
    borderRadius: 10,
    marginBottom: 10,
  },
  heroTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  heroTitleWrap: {
    flex: 1,
    marginRight: 10,
  },
  heroTitle: {
    fontSize: 24,
    color: '#0f172a',
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  heroMeta: {
    fontSize: 10,
    color: '#475569',
    lineHeight: 1.5,
  },
  heroPrice: {
    fontSize: 22,
    color: '#0f172a',
    fontFamily: 'Helvetica-Bold',
  },
  heroPriceLabel: {
    fontSize: 9,
    color: '#64748b',
    textAlign: 'right',
  },
  sectionTitle: {
    fontSize: 12,
    color: '#334155',
    fontFamily: 'Helvetica-Bold',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  daySection: {
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    paddingBottom: 9,
  },
  dayHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  dayHeading: {
    fontSize: 12,
    color: '#0f172a',
    fontFamily: 'Helvetica-Bold',
  },
  daySubheading: {
    fontSize: 10,
    color: '#475569',
  },
  activityCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 8,
    marginBottom: 6,
  },
  activityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 3,
  },
  activityTitle: {
    fontSize: 10,
    color: '#0f172a',
    fontFamily: 'Helvetica-Bold',
    flex: 1,
    marginRight: 8,
  },
  privateBadge: {
    fontSize: 7,
    color: '#ffffff',
    backgroundColor: '#1d4ed8',
    borderRadius: 3,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 4,
    paddingRight: 4,
    textTransform: 'uppercase',
    fontFamily: 'Helvetica-Bold',
  },
  activityMeta: {
    fontSize: 8,
    color: '#475569',
    marginBottom: 2,
  },
  activityDescription: {
    fontSize: 8,
    color: '#334155',
    lineHeight: 1.35,
  },
  thumbnailRow: {
    flexDirection: 'row',
    marginTop: 5,
  },
  thumbnail: {
    width: 42,
    height: 32,
    borderRadius: 4,
    marginRight: 4,
  },
  closingPanel: {
    marginTop: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#cbd5e1',
  },
  closingTitle: {
    fontSize: 28,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'center',
    marginBottom: 6,
  },
  closingBody: {
    fontSize: 11,
    textAlign: 'center',
    color: '#475569',
    marginBottom: 6,
    lineHeight: 1.5,
  },
  closingInfo: {
    fontSize: 10,
    textAlign: 'center',
    color: '#334155',
    lineHeight: 1.4,
  },
});
