import type {
  ReputationReview,
  ReputationDashboardData,
  ReputationReviewCampaign,
  ReputationBrandVoice,
  ReputationPlatformConnection,
  ReputationCompetitor,
  ReputationWidget,
} from "@/lib/reputation/types";

// ─── Reviews ──────────────────────────────────────────────────
export const MOCK_REVIEWS: ReputationReview[] = [
  {
    id: "rev-1",
    organization_id: "org-1",
    platform: "google",
    platform_review_id: "goog-r1",
    platform_url: "https://maps.google.com/review/1",
    reviewer_name: "Priya Sharma",
    reviewer_avatar_url: null,
    rating: 5,
    title: "Best Kerala trip ever!",
    comment:
      "We had an absolutely wonderful experience. The houseboat in Alleppey was stunning, the driver was punctual and courteous, and the itinerary was perfectly planned. The food recommendations were spot-on. Would highly recommend GoBuddy Adventures to anyone visiting Kerala!",
    review_date: "2025-02-18",
    language: "en",
    trip_id: "trip-101",
    client_id: "client-1",
    destination: "Kerala",
    trip_type: "Family",
    sentiment_score: 0.92,
    sentiment_label: "positive",
    ai_topics: ["itinerary_planning", "driver_behavior", "food", "hotel_quality"],
    ai_summary: "Exceptional experience across all touchpoints — highlights houseboat, driver, and food.",
    response_status: "responded",
    response_text:
      "Thank you so much, Priya! We're thrilled your family enjoyed the Kerala houseboat experience. Your kind words about our driver and itinerary planning mean the world to us. We'd love to host you again!",
    ai_suggested_response: null,
    response_posted_at: "2025-02-19",
    response_posted_by: "owner",
    is_featured: true,
    is_verified_client: true,
    requires_attention: false,
    attention_reason: null,
    created_at: "2025-02-18T10:00:00Z",
    updated_at: "2025-02-19T08:00:00Z",
  },
  {
    id: "rev-2",
    organization_id: "org-1",
    platform: "tripadvisor",
    platform_review_id: "ta-r2",
    platform_url: "https://tripadvisor.com/review/2",
    reviewer_name: "James Wilson",
    reviewer_avatar_url: null,
    rating: 4,
    title: "Great Rajasthan tour with minor hiccups",
    comment:
      "Overall a fantastic 8-day Rajasthan tour. The palace hotels were incredible and our guide was very knowledgeable. Only issue was the car AC wasn't working well on the Jaipur-Jodhpur stretch — quite uncomfortable in the heat. Otherwise, everything was well organized.",
    review_date: "2025-02-15",
    language: "en",
    trip_id: "trip-102",
    client_id: "client-2",
    destination: "Rajasthan",
    trip_type: "Couple",
    sentiment_score: 0.65,
    sentiment_label: "positive",
    ai_topics: ["hotel_quality", "guide_quality", "transport", "itinerary_planning"],
    ai_summary: "Positive overall — praises hotels and guide, flags transport AC issue on one leg.",
    response_status: "pending",
    response_text: null,
    ai_suggested_response:
      "Dear James, thank you for sharing your experience! We're delighted the palace hotels and our guide exceeded expectations. We sincerely apologize about the AC issue on the Jaipur-Jodhpur drive — we've flagged this with our vehicle partner to ensure it doesn't happen again. We hope to welcome you back to India!",
    response_posted_at: null,
    response_posted_by: null,
    is_featured: false,
    is_verified_client: true,
    requires_attention: true,
    attention_reason: "Transport complaint needs acknowledgment",
    created_at: "2025-02-15T14:00:00Z",
    updated_at: "2025-02-15T14:00:00Z",
  },
  {
    id: "rev-3",
    organization_id: "org-1",
    platform: "google",
    platform_review_id: "goog-r3",
    platform_url: "https://maps.google.com/review/3",
    reviewer_name: "Ananya Patel",
    reviewer_avatar_url: null,
    rating: 5,
    title: "Perfect honeymoon in Goa",
    comment:
      "My husband and I had the most romantic honeymoon thanks to GoBuddy. The beachfront resort was gorgeous, the candlelight dinner setup was a beautiful surprise, and the sunset cruise was unforgettable. Everything was seamless from start to finish.",
    review_date: "2025-02-10",
    language: "en",
    trip_id: "trip-103",
    client_id: "client-3",
    destination: "Goa",
    trip_type: "Honeymoon",
    sentiment_score: 0.95,
    sentiment_label: "positive",
    ai_topics: ["hotel_quality", "itinerary_planning", "local_experience"],
    ai_summary: "Glowing honeymoon review — all touchpoints exceeded expectations.",
    response_status: "responded",
    response_text: "Thank you Ananya! What a joy to be part of your honeymoon celebrations.",
    ai_suggested_response: null,
    response_posted_at: "2025-02-11",
    response_posted_by: "owner",
    is_featured: true,
    is_verified_client: true,
    requires_attention: false,
    attention_reason: null,
    created_at: "2025-02-10T09:00:00Z",
    updated_at: "2025-02-11T07:00:00Z",
  },
  {
    id: "rev-4",
    organization_id: "org-1",
    platform: "makemytrip",
    platform_review_id: "mmt-r4",
    platform_url: "https://makemytrip.com/review/4",
    reviewer_name: "Rajesh Kumar",
    reviewer_avatar_url: null,
    rating: 2,
    title: "Disappointing Shimla experience",
    comment:
      "The hotel was not as described — room was much smaller and didn't have the mountain view promised. Driver was late on two occasions. The only saving grace was the food recommendations. Would not recommend at this price point.",
    review_date: "2025-02-08",
    language: "en",
    trip_id: "trip-104",
    client_id: "client-4",
    destination: "Shimla",
    trip_type: "Family",
    sentiment_score: -0.72,
    sentiment_label: "negative",
    ai_topics: ["hotel_quality", "driver_behavior", "value_for_money", "communication"],
    ai_summary: "Negative — hotel mismatch, driver punctuality issues, perceived poor value.",
    response_status: "pending",
    response_text: null,
    ai_suggested_response:
      "Dear Rajesh, we're truly sorry about your experience. The hotel discrepancy and driver delays are unacceptable and not reflective of our standards. We've already addressed these issues with our partners. We'd like to make this right — please reach out to us directly so we can discuss a resolution.",
    response_posted_at: null,
    response_posted_by: null,
    is_featured: false,
    is_verified_client: true,
    requires_attention: true,
    attention_reason: "Negative review with hotel mismatch complaint — needs urgent response",
    created_at: "2025-02-08T16:00:00Z",
    updated_at: "2025-02-08T16:00:00Z",
  },
  {
    id: "rev-5",
    organization_id: "org-1",
    platform: "facebook",
    platform_review_id: "fb-r5",
    platform_url: "https://facebook.com/review/5",
    reviewer_name: "Sarah Chen",
    reviewer_avatar_url: null,
    rating: 5,
    title: null,
    comment:
      "Incredible Golden Triangle tour! Delhi, Agra, and Jaipur were all amazing. Our guide knew so much history and made every monument come alive. The Taj Mahal at sunrise was a once-in-a-lifetime experience. Thank you GoBuddy!",
    review_date: "2025-02-05",
    language: "en",
    trip_id: "trip-105",
    client_id: "client-5",
    destination: "Delhi-Agra-Jaipur",
    trip_type: "Solo",
    sentiment_score: 0.88,
    sentiment_label: "positive",
    ai_topics: ["guide_quality", "local_experience", "itinerary_planning"],
    ai_summary: "Enthusiastic Golden Triangle review, highlights guide expertise and Taj sunrise.",
    response_status: "responded",
    response_text: "Thank you Sarah! So glad our guide brought the history alive for you.",
    ai_suggested_response: null,
    response_posted_at: "2025-02-06",
    response_posted_by: "owner",
    is_featured: false,
    is_verified_client: false,
    requires_attention: false,
    attention_reason: null,
    created_at: "2025-02-05T12:00:00Z",
    updated_at: "2025-02-06T09:00:00Z",
  },
  {
    id: "rev-6",
    organization_id: "org-1",
    platform: "google",
    platform_review_id: "goog-r6",
    platform_url: null,
    reviewer_name: "Michael Torres",
    reviewer_avatar_url: null,
    rating: 4,
    title: "Solid Ladakh adventure",
    comment:
      "Challenging but rewarding trip to Ladakh. The permits and logistics were handled perfectly. Hotels were basic but clean. The Pangong Lake camping was a highlight. Only wish the acclimatization day had more activities planned.",
    review_date: "2025-01-28",
    language: "en",
    trip_id: "trip-106",
    client_id: "client-6",
    destination: "Ladakh",
    trip_type: "Adventure",
    sentiment_score: 0.55,
    sentiment_label: "positive",
    ai_topics: ["itinerary_planning", "hotel_quality", "local_experience", "flexibility"],
    ai_summary: "Positive adventure review, minor feedback on acclimatization day planning.",
    response_status: "not_needed",
    response_text: null,
    ai_suggested_response: null,
    response_posted_at: null,
    response_posted_by: null,
    is_featured: false,
    is_verified_client: true,
    requires_attention: false,
    attention_reason: null,
    created_at: "2025-01-28T08:00:00Z",
    updated_at: "2025-01-28T08:00:00Z",
  },
  {
    id: "rev-7",
    organization_id: "org-1",
    platform: "tripadvisor",
    platform_review_id: "ta-r7",
    platform_url: null,
    reviewer_name: "Deepika Nair",
    reviewer_avatar_url: null,
    rating: 3,
    title: "Average Munnar trip",
    comment:
      "The tea plantation visit was nice but the rest of the trip felt rushed. Hotel was okay, nothing special. Communication before the trip was great but during the trip we couldn't reach anyone easily. Would be better with a dedicated point of contact.",
    review_date: "2025-01-25",
    language: "en",
    trip_id: "trip-107",
    client_id: "client-7",
    destination: "Munnar",
    trip_type: "Couple",
    sentiment_score: 0.05,
    sentiment_label: "neutral",
    ai_topics: ["communication", "itinerary_planning", "hotel_quality", "local_experience"],
    ai_summary: "Mixed — good pre-trip communication but on-trip reachability was poor.",
    response_status: "draft",
    response_text: "Hi Deepika, thank you for the honest feedback...",
    ai_suggested_response:
      "Dear Deepika, we appreciate your candid feedback. You're absolutely right that on-trip communication is crucial. We've now set up a dedicated WhatsApp line for all active trips so guests can reach us instantly. We hope to show you an improved experience next time!",
    response_posted_at: null,
    response_posted_by: null,
    is_featured: false,
    is_verified_client: true,
    requires_attention: true,
    attention_reason: "Communication gap highlighted — needs operational fix",
    created_at: "2025-01-25T11:00:00Z",
    updated_at: "2025-01-26T10:00:00Z",
  },
  {
    id: "rev-8",
    organization_id: "org-1",
    platform: "internal",
    platform_review_id: null,
    platform_url: null,
    reviewer_name: "Arun Mehta",
    reviewer_avatar_url: null,
    rating: 5,
    title: "Outstanding Andaman trip",
    comment:
      "Every single detail was taken care of. The snorkeling trip was the highlight for our kids. Ferry bookings, hotel check-ins, everything was pre-arranged. Best family vacation we've had!",
    review_date: "2025-01-20",
    language: "en",
    trip_id: "trip-108",
    client_id: "client-8",
    destination: "Andaman",
    trip_type: "Family",
    sentiment_score: 0.91,
    sentiment_label: "positive",
    ai_topics: ["itinerary_planning", "booking_process", "local_experience", "safety"],
    ai_summary: "Exceptional family vacation — praises end-to-end logistics and activities.",
    response_status: "responded",
    response_text: "Thank you Arun! Thrilled the kids loved the snorkeling!",
    ai_suggested_response: null,
    response_posted_at: "2025-01-21",
    response_posted_by: "owner",
    is_featured: true,
    is_verified_client: true,
    requires_attention: false,
    attention_reason: null,
    created_at: "2025-01-20T15:00:00Z",
    updated_at: "2025-01-21T08:00:00Z",
  },
];

// ─── Dashboard Overview Data ──────────────────────────────────
export const MOCK_DASHBOARD_DATA: ReputationDashboardData = {
  overallRating: 4.3,
  totalReviews: 156,
  responseRate: 78,
  npsScore: 62,
  healthScore: 72,
  healthFactors: {
    avgRating: 4.3,
    responseRate: 78,
    avgResponseTimeHours: 8.5,
    reviewVelocity: 12,
    sentimentRatio: 0.82,
  },
  platformBreakdown: [
    { platform: "google", rating: 4.5, count: 68, label: "Google", color: "#4285F4" },
    { platform: "tripadvisor", rating: 4.2, count: 42, label: "TripAdvisor", color: "#34E0A1" },
    { platform: "facebook", rating: 4.1, count: 18, label: "Facebook", color: "#1877F2" },
    { platform: "makemytrip", rating: 4.0, count: 16, label: "MakeMyTrip", color: "#EB2026" },
    { platform: "internal", rating: 4.6, count: 12, label: "Direct Feedback", color: "#8B5CF6" },
  ],
  ratingDistribution: { 5: 72, 4: 48, 3: 22, 2: 10, 1: 4 },
  sentimentBreakdown: { positive: 112, neutral: 28, negative: 16 },
  recentReviews: [],
  attentionCount: 3,
  trendsData: [
    { date: "2024-09", rating: 4.1, reviewCount: 12, healthScore: 65 },
    { date: "2024-10", rating: 4.0, reviewCount: 15, healthScore: 63 },
    { date: "2024-11", rating: 4.2, reviewCount: 18, healthScore: 68 },
    { date: "2024-12", rating: 4.3, reviewCount: 14, healthScore: 70 },
    { date: "2025-01", rating: 4.4, reviewCount: 20, healthScore: 74 },
    { date: "2025-02", rating: 4.3, reviewCount: 16, healthScore: 72 },
  ],
};

// ─── Campaigns ────────────────────────────────────────────────
export const MOCK_CAMPAIGNS: ReputationReviewCampaign[] = [
  {
    id: "camp-1",
    organization_id: "org-1",
    name: "Post-Trip Review Request",
    campaign_type: "post_trip",
    status: "active",
    trigger_event: "trip_completed",
    trigger_delay_hours: 24,
    target_rating_minimum: 1,
    promoter_threshold: 9,
    passive_threshold: 7,
    promoter_action: "google_review_link",
    promoter_review_url: "https://maps.google.com/review/place123",
    detractor_action: "internal_feedback",
    channel_sequence: ["whatsapp", "email"],
    whatsapp_template_name: "post_trip_nps",
    email_template_id: "tmpl-email-1",
    nps_question: "How likely are you to recommend us to a friend or colleague?",
    nps_followup_question: "What could we have done better?",
    stats_sent: 342,
    stats_opened: 289,
    stats_completed: 198,
    stats_reviews_generated: 86,
    created_at: "2024-11-01T00:00:00Z",
    updated_at: "2025-02-20T00:00:00Z",
  },
  {
    id: "camp-2",
    organization_id: "org-1",
    name: "Mid-Trip Check-In",
    campaign_type: "mid_trip_checkin",
    status: "active",
    trigger_event: "trip_day_2",
    trigger_delay_hours: 0,
    target_rating_minimum: 1,
    promoter_threshold: 9,
    passive_threshold: 7,
    promoter_action: "google_review_link",
    promoter_review_url: null,
    detractor_action: "escalate_owner",
    channel_sequence: ["whatsapp"],
    whatsapp_template_name: "mid_trip_checkin",
    email_template_id: null,
    nps_question: "How is your trip going so far?",
    nps_followup_question: "Is there anything we can improve right now?",
    stats_sent: 156,
    stats_opened: 142,
    stats_completed: 98,
    stats_reviews_generated: 12,
    created_at: "2024-12-15T00:00:00Z",
    updated_at: "2025-02-18T00:00:00Z",
  },
  {
    id: "camp-3",
    organization_id: "org-1",
    name: "Quarterly NPS Survey",
    campaign_type: "nps_survey",
    status: "paused",
    trigger_event: "manual",
    trigger_delay_hours: 0,
    target_rating_minimum: 1,
    promoter_threshold: 9,
    passive_threshold: 7,
    promoter_action: "tripadvisor_link",
    promoter_review_url: "https://tripadvisor.com/review/place456",
    detractor_action: "private_form",
    channel_sequence: ["email", "whatsapp"],
    whatsapp_template_name: "nps_quarterly",
    email_template_id: "tmpl-email-2",
    nps_question: "On a scale of 0-10, how likely are you to recommend GoBuddy Adventures?",
    nps_followup_question: "What's the primary reason for your score?",
    stats_sent: 89,
    stats_opened: 67,
    stats_completed: 45,
    stats_reviews_generated: 18,
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-02-01T00:00:00Z",
  },
];

// ─── Sentiment Chart Data ─────────────────────────────────────
export const MOCK_SENTIMENT_DATA = [
  { date: "Sep 2024", positive: 15, neutral: 4, negative: 2 },
  { date: "Oct 2024", positive: 18, neutral: 5, negative: 3 },
  { date: "Nov 2024", positive: 22, neutral: 3, negative: 2 },
  { date: "Dec 2024", positive: 16, neutral: 6, negative: 3 },
  { date: "Jan 2025", positive: 24, neutral: 5, negative: 2 },
  { date: "Feb 2025", positive: 17, neutral: 5, negative: 4 },
];

// ─── Topic Cloud Data ─────────────────────────────────────────
export const MOCK_TOPICS = [
  { topic: "itinerary_planning", count: 68, sentiment: "positive" as const },
  { topic: "hotel_quality", count: 54, sentiment: "positive" as const },
  { topic: "guide_quality", count: 42, sentiment: "positive" as const },
  { topic: "driver_behavior", count: 38, sentiment: "positive" as const },
  { topic: "food", count: 35, sentiment: "positive" as const },
  { topic: "local_experience", count: 32, sentiment: "positive" as const },
  { topic: "value_for_money", count: 28, sentiment: "neutral" as const },
  { topic: "communication", count: 24, sentiment: "neutral" as const },
  { topic: "transport", count: 22, sentiment: "negative" as const },
  { topic: "booking_process", count: 18, sentiment: "positive" as const },
  { topic: "safety", count: 15, sentiment: "positive" as const },
  { topic: "punctuality", count: 12, sentiment: "neutral" as const },
  { topic: "cleanliness", count: 10, sentiment: "positive" as const },
  { topic: "flexibility", count: 8, sentiment: "positive" as const },
  { topic: "weather", count: 5, sentiment: "neutral" as const },
];

// ─── Review-to-Revenue Data ───────────────────────────────────
export const MOCK_REVENUE_DATA = [
  { month: "Sep 2024", avgRating: 4.1, bookings: 28 },
  { month: "Oct 2024", avgRating: 4.0, bookings: 32 },
  { month: "Nov 2024", avgRating: 4.2, bookings: 38 },
  { month: "Dec 2024", avgRating: 4.3, bookings: 45 },
  { month: "Jan 2025", avgRating: 4.4, bookings: 52 },
  { month: "Feb 2025", avgRating: 4.3, bookings: 48 },
];

// ─── Competitors ──────────────────────────────────────────────
export const MOCK_COMPETITORS: ReputationCompetitor[] = [
  {
    id: "comp-1",
    organization_id: "org-1",
    competitor_name: "WanderLux India",
    google_place_id: "place-wl",
    tripadvisor_url: "https://tripadvisor.com/wanderlux",
    website_url: "https://wanderluxindia.com",
    latest_rating: 4.5,
    latest_review_count: 234,
    last_checked_at: "2025-02-20T00:00:00Z",
    created_at: "2024-10-01T00:00:00Z",
    updated_at: "2025-02-20T00:00:00Z",
  },
  {
    id: "comp-2",
    organization_id: "org-1",
    competitor_name: "Royal India Tours",
    google_place_id: "place-rit",
    tripadvisor_url: "https://tripadvisor.com/royalindia",
    website_url: "https://royalindiatours.com",
    latest_rating: 4.1,
    latest_review_count: 189,
    last_checked_at: "2025-02-20T00:00:00Z",
    created_at: "2024-10-01T00:00:00Z",
    updated_at: "2025-02-20T00:00:00Z",
  },
  {
    id: "comp-3",
    organization_id: "org-1",
    competitor_name: "Incredible Journeys",
    google_place_id: "place-ij",
    tripadvisor_url: null,
    website_url: "https://incrediblejourneys.in",
    latest_rating: 3.8,
    latest_review_count: 97,
    last_checked_at: "2025-02-20T00:00:00Z",
    created_at: "2024-11-15T00:00:00Z",
    updated_at: "2025-02-20T00:00:00Z",
  },
];

// ─── Platform Connections ─────────────────────────────────────
export const MOCK_CONNECTIONS: ReputationPlatformConnection[] = [
  {
    id: "conn-1",
    organization_id: "org-1",
    platform: "google_business",
    platform_account_id: "gbp-123",
    platform_account_name: "GoBuddy Adventures",
    platform_location_id: "loc-456",
    sync_enabled: true,
    last_synced_at: "2025-02-20T14:30:00Z",
    sync_cursor: "cursor-abc",
    sync_error: null,
    created_at: "2024-09-01T00:00:00Z",
    updated_at: "2025-02-20T14:30:00Z",
  },
  {
    id: "conn-2",
    organization_id: "org-1",
    platform: "tripadvisor",
    platform_account_id: "ta-789",
    platform_account_name: "GoBuddy Adventures",
    platform_location_id: null,
    sync_enabled: true,
    last_synced_at: "2025-02-20T12:00:00Z",
    sync_cursor: "cursor-def",
    sync_error: null,
    created_at: "2024-09-15T00:00:00Z",
    updated_at: "2025-02-20T12:00:00Z",
  },
];

// ─── Brand Voice ──────────────────────────────────────────────
export const MOCK_BRAND_VOICE: ReputationBrandVoice = {
  id: "bv-1",
  organization_id: "org-1",
  tone: "professional_warm",
  language_preference: "en",
  owner_name: "Avinash",
  sign_off: "Warm regards, The GoBuddy Adventures Team",
  key_phrases: [
    "personalized experience",
    "handcrafted itinerary",
    "local expertise",
    "unforgettable memories",
  ],
  avoid_phrases: ["cheap", "budget", "discount", "sorry for the inconvenience"],
  sample_responses: [
    "Thank you for choosing GoBuddy Adventures! We're thrilled you enjoyed your experience.",
    "We appreciate your honest feedback — it helps us improve every trip we craft.",
  ],
  auto_respond_positive: false,
  auto_respond_min_rating: 4,
  escalation_threshold: 2,
  created_at: "2024-09-01T00:00:00Z",
  updated_at: "2025-02-15T00:00:00Z",
};

// ─── Widget ───────────────────────────────────────────────────
export const MOCK_WIDGET: ReputationWidget = {
  id: "widget-1",
  organization_id: "org-1",
  name: "Website Review Widget",
  widget_type: "carousel",
  theme: "light",
  accent_color: "#00d084",
  background_color: null,
  text_color: null,
  border_radius: 12,
  min_rating_to_show: 4,
  max_reviews: 10,
  platforms_filter: ["google", "tripadvisor"],
  destinations_filter: [],
  embed_token: "embed-tok-abc123",
  is_active: true,
  show_branding: true,
  custom_header: "What Our Travelers Say",
  custom_footer: null,
  created_at: "2024-10-01T00:00:00Z",
  updated_at: "2025-02-10T00:00:00Z",
};
