export const REPUTATION_BRAND_VOICE_SELECT = [
  "auto_respond_min_rating",
  "auto_respond_positive",
  "avoid_phrases",
  "created_at",
  "escalation_threshold",
  "id",
  "key_phrases",
  "language_preference",
  "organization_id",
  "owner_name",
  "sample_responses",
  "sign_off",
  "tone",
  "updated_at",
].join(", ");

export const REPUTATION_CAMPAIGN_SEND_SELECT = [
  "campaign_id",
  "client_email",
  "client_id",
  "client_name",
  "client_phone",
  "completed_at",
  "created_at",
  "delivered_at",
  "id",
  "notification_queue_id",
  "nps_feedback",
  "nps_score",
  "nps_submitted_at",
  "nps_token",
  "nps_token_expires_at",
  "opened_at",
  "organization_id",
  "review_link",
  "review_link_clicked",
  "review_link_clicked_at",
  "review_submitted",
  "review_submitted_at",
  "routed_to",
  "sent_at",
  "status",
  "trip_id",
  "updated_at",
].join(", ");

export const REPUTATION_PLATFORM_CONNECTION_SELECT = [
  "access_token_encrypted",
  "created_at",
  "id",
  "last_synced_at",
  "organization_id",
  "platform",
  "platform_account_id",
  "platform_account_name",
  "platform_location_id",
  "refresh_token_encrypted",
  "sync_cursor",
  "sync_enabled",
  "sync_error",
  "token_expires_at",
  "updated_at",
].join(", ");

export const REPUTATION_REVIEW_CAMPAIGN_SELECT = [
  "campaign_type",
  "channel_sequence",
  "created_at",
  "detractor_action",
  "email_template_id",
  "id",
  "name",
  "nps_followup_question",
  "nps_question",
  "organization_id",
  "passive_threshold",
  "promoter_action",
  "promoter_review_url",
  "promoter_threshold",
  "stats_completed",
  "stats_opened",
  "stats_reviews_generated",
  "stats_sent",
  "status",
  "target_rating_minimum",
  "trigger_delay_hours",
  "trigger_event",
  "updated_at",
  "whatsapp_template_name",
].join(", ");

export const REPUTATION_REVIEW_SELECT = [
  "ai_suggested_response",
  "ai_summary",
  "ai_topics",
  "attention_reason",
  "client_id",
  "comment",
  "created_at",
  "destination",
  "id",
  "is_featured",
  "is_verified_client",
  "language",
  "organization_id",
  "platform",
  "platform_review_id",
  "platform_url",
  "rating",
  "requires_attention",
  "response_posted_at",
  "response_posted_by",
  "response_status",
  "response_text",
  "review_date",
  "reviewer_avatar_url",
  "reviewer_name",
  "sentiment_label",
  "sentiment_score",
  "title",
  "trip_id",
  "trip_type",
  "updated_at",
].join(", ");

export const REPUTATION_SNAPSHOT_SELECT = [
  "avg_response_time_hours",
  "created_at",
  "facebook_count",
  "facebook_rating",
  "google_count",
  "google_rating",
  "health_score",
  "id",
  "internal_count",
  "internal_rating",
  "makemytrip_count",
  "makemytrip_rating",
  "negative_count",
  "neutral_count",
  "nps_score",
  "organization_id",
  "overall_rating",
  "positive_count",
  "response_rate",
  "review_requests_converted",
  "review_requests_sent",
  "snapshot_date",
  "total_review_count",
  "tripadvisor_count",
  "tripadvisor_rating",
].join(", ");

export const REPUTATION_WIDGET_SELECT = [
  "accent_color",
  "background_color",
  "border_radius",
  "created_at",
  "custom_footer",
  "custom_header",
  "destinations_filter",
  "embed_token",
  "id",
  "is_active",
  "max_reviews",
  "min_rating_to_show",
  "name",
  "organization_id",
  "platforms_filter",
  "show_branding",
  "text_color",
  "theme",
  "updated_at",
  "widget_type",
].join(", ");

export const REPUTATION_WIDGET_PUBLIC_REVIEW_SELECT = [
  "id",
  "platform",
  "reviewer_name",
  "reviewer_avatar_url",
  "rating",
  "title",
  "comment",
  "review_date",
  "destination",
  "is_verified_client",
].join(", ");
