// ---------------------------------------------------------------------------
// Layout configuration and dimension constants
// ---------------------------------------------------------------------------

import type { AspectRatio, LayoutType } from "./types";
import type { LayoutConfig, Dimensions } from "./poster-renderer-types";

// ---------------------------------------------------------------------------
// Dimensions
// ---------------------------------------------------------------------------

export const DIMENSIONS: Record<AspectRatio, Dimensions> = {
  square: { width: 1080, height: 1080 },
  portrait: { width: 1080, height: 1350 },
  story: { width: 1080, height: 1920 },
};

// ---------------------------------------------------------------------------
// Layout configuration per layout type
// ---------------------------------------------------------------------------

export const LAYOUT_CONFIGS: Record<LayoutType, LayoutConfig> = {
  CenterLayout: {
    headerPosition: "top-center",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "bottom-fade",
    heroFontFamily: "Cormorant Garamond",
    heroFontSize: 80,
  },
  SplitLayout: {
    headerPosition: "top-left",
    heroPosition: "center",
    pricePosition: "bottom-right",
    footerStyle: "bottom-bar",
    overlayGradient: "diagonal",
    heroFontFamily: "Inter",
    heroFontSize: 72,
  },
  BottomLayout: {
    headerPosition: "top-center",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "bottom-fade",
    heroFontFamily: "Inter",
    heroFontSize: 80,
  },
  ElegantLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "inline",
    overlayGradient: "full-dark",
    heroFontFamily: "Cormorant Garamond",
    heroFontSize: 88,
  },
  ReviewLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "none",
    heroFontFamily: "Cormorant Garamond",
    heroFontSize: 36,
  },
  ServiceShowcaseLayout: {
    headerPosition: "top-center",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "navy-bar",
    overlayGradient: "none",
    heroFontFamily: "Inter",
    heroFontSize: 64,
  },
  HeroServicesLayout: {
    headerPosition: "top-left",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "navy-bar",
    overlayGradient: "bottom-fade",
    heroFontFamily: "Inter",
    heroFontSize: 72,
  },
  InfoSplitLayout: {
    headerPosition: "top-left",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "navy-bar",
    overlayGradient: "diagonal",
    heroFontFamily: "Inter",
    heroFontSize: 64,
  },
  GradientHeroLayout: {
    headerPosition: "top-left",
    heroPosition: "center-large",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "bottom-fade",
    heroFontFamily: "Playfair Display",
    heroFontSize: 96,
  },
  DiagonalSplitLayout: {
    headerPosition: "top-left",
    heroPosition: "center",
    pricePosition: "bottom-right",
    footerStyle: "navy-bar",
    overlayGradient: "diagonal",
    heroFontFamily: "Montserrat",
    heroFontSize: 72,
  },
  MagazineCoverLayout: {
    headerPosition: "top-left",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "inline",
    overlayGradient: "bottom-fade",
    heroFontFamily: "Playfair Display",
    heroFontSize: 88,
  },
  DuotoneLayout: {
    headerPosition: "top-left",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "inline",
    overlayGradient: "full-dark",
    heroFontFamily: "Montserrat",
    heroFontSize: 80,
  },
  BoldTypographyLayout: {
    headerPosition: "top-center",
    heroPosition: "center-large",
    pricePosition: "center-below",
    footerStyle: "navy-bar",
    overlayGradient: "bottom-fade",
    heroFontFamily: "Montserrat",
    heroFontSize: 96,
  },
  CarouselSlideLayout: {
    headerPosition: "top-left",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "bottom-fade",
    heroFontFamily: "Inter",
    heroFontSize: 64,
  },
  CollageGridLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "bottom-bar",
    overlayGradient: "bottom-fade",
    heroFontFamily: "Poppins",
    heroFontSize: 72,
  },
  TriPanelLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "bottom-bar",
    overlayGradient: "none",
    heroFontFamily: "Poppins",
    heroFontSize: 64,
  },
  PolaroidScatterLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "bottom-bar",
    overlayGradient: "none",
    heroFontFamily: "Inter",
    heroFontSize: 60,
  },
  WindowGalleryLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "bottom-bar",
    overlayGradient: "none",
    heroFontFamily: "Cormorant Garamond",
    heroFontSize: 64,
  },
  MosaicStripLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "bottom-bar",
    overlayGradient: "none",
    heroFontFamily: "Poppins",
    heroFontSize: 60,
  },
  // Premium layouts -- text overlays handled by buildPremiumTextJsx
  WaveDividerLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "none",
    heroFontFamily: "Playfair Display",
    heroFontSize: 72,
  },
  CircleAccentLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "none",
    heroFontFamily: "Poppins",
    heroFontSize: 64,
  },
  FloatingCardLayout: {
    headerPosition: "top-left",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "vignette",
    heroFontFamily: "Playfair Display",
    heroFontSize: 80,
  },
  PremiumCollageLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "bottom-bar",
    overlayGradient: "none",
    heroFontFamily: "Montserrat",
    heroFontSize: 72,
  },
  BannerRibbonLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "center-below",
    footerStyle: "navy-bar",
    overlayGradient: "none",
    heroFontFamily: "Playfair Display",
    heroFontSize: 80,
  },
  SplitWaveLayout: {
    headerPosition: "none",
    heroPosition: "center",
    pricePosition: "bottom-left",
    footerStyle: "navy-bar",
    overlayGradient: "none",
    heroFontFamily: "Poppins",
    heroFontSize: 64,
  },
};
