import { SocialTemplate } from './types';

export const templates: SocialTemplate[] = [
    // ─── FESTIVAL ───────────────────────────────────────────────────────────────
    {
        id: "holi_special_1",
        name: "Festival of Colors",
        category: "Festival",
        subcategory: "Holi",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holi", "colors", "offer", "spring"],
        seasonalAvailability: ["holi_2026"],
        defaultText: {
            headline: "Happy Holi!",
            subheadline: "May your life be filled with vibrant colors",
            body: "Special 20% off on all domestic packages this Holi."
        }
    },
    {
        id: "holi_special_2",
        name: "Holi Splash Sale",
        category: "Festival",
        subcategory: "Holi",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holi", "sale", "festival"],
        seasonalAvailability: ["holi_2026"],
    },
    {
        id: "diwali_grand_offer",
        name: "Diwali Grand Sale",
        category: "Festival",
        subcategory: "Diwali",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["diwali", "sale", "festive"],
        seasonalAvailability: ["diwali_2026"],
    },
    {
        id: "diwali_lights_2",
        name: "Diwali Glow",
        category: "Festival",
        subcategory: "Diwali",
        layout: "BottomLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["diwali", "lights", "luxury"],
        seasonalAvailability: ["diwali_2026"],
    },
    {
        id: "christmas_travel_1",
        name: "Christmas Getaway",
        category: "Festival",
        subcategory: "Christmas",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["christmas", "winter", "holiday", "getaway"],
        seasonalAvailability: ["christmas_2026"],
    },
    {
        id: "christmas_package_2",
        name: "Xmas Package Deal",
        category: "Festival",
        subcategory: "Christmas",
        layout: "SplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["christmas", "package", "family"],
        seasonalAvailability: ["christmas_2026"],
    },
    {
        id: "navratri_special_1",
        name: "Navratri Package",
        category: "Festival",
        subcategory: "Navratri",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["navratri", "garba", "gujarat", "festival"],
        seasonalAvailability: ["navratri_2026"],
    },
    {
        id: "eid_mubarak_1",
        name: "Eid Mubarak Travel",
        category: "Festival",
        subcategory: "Eid",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["eid", "mubarak", "holiday", "tour"],
    },
    {
        id: "independence_day_1",
        name: "Freedom Sale",
        category: "Festival",
        subcategory: "Independence Day",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["independence", "india", "sale", "tricolor"],
        seasonalAvailability: ["independence_day_2026"],
    },
    {
        id: "new_year_1",
        name: "New Year Escape",
        category: "Festival",
        subcategory: "New Year",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["new year", "celebration", "travel", "2027"],
    },

    // ─── SEASON ─────────────────────────────────────────────────────────────────
    {
        id: "summer_beach_1",
        name: "Summer Beach Escape",
        category: "Season",
        subcategory: "Summer",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["summer", "beach", "escape", "hot"],
    },
    {
        id: "summer_special_2",
        name: "Hot Summer Deals",
        category: "Season",
        subcategory: "Summer",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["summer", "deal", "sale", "vacation"],
    },
    {
        id: "monsoon_magic_1",
        name: "Monsoon Magic",
        category: "Season",
        subcategory: "Monsoon",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["monsoon", "rain", "kerala", "nature"],
    },
    {
        id: "winter_hills_1",
        name: "Winter Hills Special",
        category: "Season",
        subcategory: "Winter",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["winter", "snow", "manali", "hills"],
    },

    // ─── DESTINATION ────────────────────────────────────────────────────────────
    {
        id: "destination_dubai_1",
        name: "Dubai Skyline",
        category: "Destination",
        subcategory: "Dubai",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["dubai", "uae", "luxury", "burj"],
    },
    {
        id: "destination_bali_1",
        name: "Bali Paradise",
        category: "Destination",
        subcategory: "Bali",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["bali", "indonesia", "paradise", "tropical"],
    },
    {
        id: "destination_maldives_1",
        name: "Maldives Luxury",
        category: "Destination",
        subcategory: "Maldives",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["maldives", "luxury", "overwater", "island"],
    },
    {
        id: "destination_kashmir_1",
        name: "Kashmir Valley",
        category: "Destination",
        subcategory: "Kashmir",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["kashmir", "valley", "snow", "paradise"],
    },
    {
        id: "destination_europe_1",
        name: "Europe Explorer",
        category: "Destination",
        subcategory: "Europe",
        layout: "BottomLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["europe", "paris", "rome", "travel"],
    },
    {
        id: "destination_thailand_1",
        name: "Thailand Adventure",
        category: "Destination",
        subcategory: "Thailand",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["thailand", "bangkok", "phuket", "asia"],
    },
    {
        id: "destination_kerala_1",
        name: "God's Own Country",
        category: "Destination",
        subcategory: "Kerala",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["kerala", "backwaters", "ayurveda", "india"],
    },

    // ─── PACKAGE TYPE ────────────────────────────────────────────────────────────
    {
        id: "honeymoon_paradise",
        name: "Honeymoon Paradise",
        category: "Package Type",
        subcategory: "Honeymoon",
        layout: "CenterLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["maldives", "honeymoon", "romantic", "couples"],
    },
    {
        id: "honeymoon_europe",
        name: "Romantic Europe",
        category: "Package Type",
        subcategory: "Honeymoon",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["europe", "honeymoon", "paris", "romantic"],
    },
    {
        id: "family_fun_1",
        name: "Family Fun Pack",
        category: "Package Type",
        subcategory: "Family",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["family", "kids", "fun", "vacation"],
    },
    {
        id: "adventure_trip_1",
        name: "Adventure Awaits",
        category: "Package Type",
        subcategory: "Adventure",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["adventure", "trek", "camping", "mountains"],
    },
    {
        id: "luxury_escape_1",
        name: "Luxury Escape",
        category: "Package Type",
        subcategory: "Luxury",
        layout: "ElegantLayout",
        tier: "Business",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["luxury", "premium", "5star", "exclusive"],
    },
    {
        id: "corporate_travel_1",
        name: "Corporate Travel",
        category: "Package Type",
        subcategory: "Corporate",
        layout: "SplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["corporate", "business", "mice", "conference"],
    },

    // ─── PROMOTION ───────────────────────────────────────────────────────────────
    {
        id: "flash_sale_1",
        name: "Flash Sale 48Hr",
        category: "Promotion",
        subcategory: "Flash Sale",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["flash sale", "urgent", "48hr", "deal"],
    },
    {
        id: "early_bird_1",
        name: "Early Bird Offer",
        category: "Promotion",
        subcategory: "Early Bird",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["early bird", "book now", "save", "advance"],
    },
    {
        id: "group_discount_1",
        name: "Group Discount",
        category: "Promotion",
        subcategory: "Group",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["group", "discount", "10+", "friends"],
    },
    {
        id: "last_minute_1",
        name: "Last Minute Deal",
        category: "Promotion",
        subcategory: "Last Minute",
        layout: "CenterLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["last minute", "deal", "urgent", "limited"],
    },

    // ─── REVIEW ──────────────────────────────────────────────────────────────────
    {
        id: "review_stars_minimal",
        name: "Minimalist Stars Review",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["review", "customer love", "5star"],
    },
    {
        id: "review_dark_quote",
        name: "Dark Quote Card",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["review", "quote", "testimonial", "dark"],
    },
    {
        id: "review_elegant_1",
        name: "Elegant Testimonial",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["review", "elegant", "branded", "testimonial"],
    },

    // ─── CAROUSEL ────────────────────────────────────────────────────────────────
    {
        id: "trip_highlights_carousel",
        name: "Trip Highlights",
        category: "Carousel",
        layout: "CarouselSlideLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["carousel", "highlights", "photos", "trip"],
        isCarousel: true,
    },
    {
        id: "day_by_day_carousel",
        name: "Day-by-Day Itinerary",
        category: "Carousel",
        layout: "CarouselSlideLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["carousel", "itinerary", "day by day", "trip"],
        isCarousel: true,
    },

    // ─── INFORMATIONAL ───────────────────────────────────────────────────────────
    {
        id: "services_overview",
        name: "Our Services",
        category: "Informational",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["services", "about", "what we offer"],
    },
    {
        id: "why_choose_us",
        name: "Why Choose Us",
        category: "Informational",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["trust", "why us", "agency", "benefits"],
    },

    // ─── SERVICE SHOWCASE (real poster format) ───────────────────────────────────
    {
        id: "service_car_luxury",
        name: "Luxury Car Service",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["car", "luxury", "transfer", "airport", "service"],
        defaultText: {
            headline: "Luxury Car Service",
            subheadline: "Comfort & Style on Every Ride",
        },
    },
    {
        id: "service_holidays_showcase",
        name: "Holiday Packages Showcase",
        category: "Package Type",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["holidays", "packages", "tour", "service", "booking"],
        defaultText: {
            headline: "Holiday Packages",
            subheadline: "Tailored Tours for Every Budget",
        },
    },
    {
        id: "service_visa_showcase",
        name: "Visa Services Card",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["visa", "services", "documentation", "passport", "apply"],
        defaultText: {
            headline: "Visa Services",
            subheadline: "Hassle-Free Visa Processing",
        },
    },
    {
        id: "service_airport_transfers",
        name: "Airport Transfers",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["airport", "transfer", "pickup", "drop", "car"],
        defaultText: {
            headline: "Airport Transfers",
            subheadline: "On-Time, Every Time",
        },
    },

    // ─── HERO SERVICES (real poster format) ─────────────────────────────────────
    {
        id: "hero_india_wonders",
        name: "Wonders of India",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["india", "wonders", "taj mahal", "heritage", "destination"],
        defaultText: {
            headline: "Wonders of India",
            subheadline: "Explore the Incredible",
        },
    },
    {
        id: "hero_asia_discover",
        name: "Discover Asia",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["asia", "discover", "southeast asia", "bali", "thailand"],
        defaultText: {
            headline: "Discover Asia",
            subheadline: "Exotic Adventures Await",
        },
    },
    {
        id: "hero_europe_dream",
        name: "Dream Europe",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["europe", "paris", "dream", "tour", "premium"],
        defaultText: {
            headline: "Dream Europe",
            subheadline: "The Trip of a Lifetime",
        },
    },

    // ─── INFO SPLIT (real poster format) ────────────────────────────────────────
    {
        id: "info_visa_split",
        name: "Get Your Visa Now",
        category: "Informational",
        layout: "InfoSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["visa", "apply", "now", "documentation", "international"],
        defaultText: {
            headline: "Get Your Visa Now",
            subheadline: "Fast • Reliable • Affordable",
        },
    },
    {
        id: "info_group_booking",
        name: "Group Booking Offer",
        category: "Promotion",
        layout: "InfoSplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["group", "booking", "offer", "corporate", "discount"],
        defaultText: {
            headline: "Group Booking Offer",
            subheadline: "Book 10+ Get Special Rates",
        },
    },
    {
        id: "info_holiday_split",
        name: "Holiday Deal Split",
        category: "Package Type",
        layout: "InfoSplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holiday", "deal", "package", "split", "offer"],
        defaultText: {
            headline: "Holiday Deal",
            subheadline: "Fly, Stay & Tour — All Included",
        },
    },
];

export function getTemplatesByCategory(category: string) {
    return templates.filter(t => t.category === category);
}

export function searchTemplates(query: string) {
    const q = query.toLowerCase();
    return templates.filter(t =>
        t.name.toLowerCase().includes(q) ||
        t.category.toLowerCase().includes(q) ||
        (t.subcategory?.toLowerCase().includes(q)) ||
        t.tags.some(tag => tag.toLowerCase().includes(q))
    );
}

export function getTemplateById(id: string) {
    return templates.find(t => t.id === id);
}

export function getTemplatesByTier(tier: string) {
    if (tier === 'Enterprise') return templates;
    if (tier === 'Business') return templates.filter(t => t.tier !== 'Enterprise');
    if (tier === 'Pro') return templates.filter(t => t.tier === 'Starter' || t.tier === 'Pro');
    return templates.filter(t => t.tier === 'Starter');
}

export const TIER_ORDER: Record<string, number> = {
    Starter: 0,
    Pro: 1,
    Business: 2,
    Enterprise: 3,
};

/** Returns true if `userTier` can access `templateTier` */
export function canAccessTemplate(templateTier: string, userTier: string = 'Starter'): boolean {
    return (TIER_ORDER[userTier] ?? 0) >= (TIER_ORDER[templateTier] ?? 0);
}
