import { SocialTemplate } from './types';

/** Festival templates — Holi, Diwali, Christmas, Navratri, Eid, Independence Day, New Year */
export const festivalTemplates: SocialTemplate[] = [
    {
        id: "holi_special_1",
        name: "Festival of Colors",
        category: "Festival",
        subcategory: "Holi",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holi", "colors", "offer", "spring"],
        seasonalAvailability: ["holi_2026"],
        defaultText: {
            headline: "Happy Holi!",
            subheadline: "May your life be filled with vibrant colors",
            body: "Special 20% off on all domestic packages this Holi."
        },
        palette: {
            bg: "bg-gradient-to-br from-rose-500 to-orange-500",
            text: "text-white",
            accent: "#ff6b6b",
            overlay: "linear-gradient(135deg, rgba(255,107,107,0.15), rgba(255,140,66,0.1))",
        },
    },
    {
        id: "holi_special_2",
        name: "Holi Splash Sale",
        category: "Festival",
        subcategory: "Holi",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holi", "sale", "festival"],
        seasonalAvailability: ["holi_2026"],
        palette: {
            bg: "bg-gradient-to-br from-rose-500 to-orange-500",
            text: "text-white",
            accent: "#ff6b6b",
            overlay: "linear-gradient(135deg, rgba(255,107,107,0.15), rgba(255,140,66,0.1))",
        },
    },
    {
        id: "diwali_grand_offer",
        name: "Diwali Grand Sale",
        category: "Festival",
        subcategory: "Diwali",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["diwali", "sale", "festive"],
        seasonalAvailability: ["diwali_2026"],
        palette: {
            bg: "bg-gradient-to-br from-amber-500 to-yellow-600",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "linear-gradient(135deg, rgba(245,158,11,0.15), rgba(234,179,8,0.1))",
        },
    },
    {
        id: "diwali_lights_2",
        name: "Diwali Glow",
        category: "Festival",
        subcategory: "Diwali",
        layout: "BottomLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["diwali", "lights", "luxury"],
        seasonalAvailability: ["diwali_2026"],
        palette: {
            bg: "bg-gradient-to-br from-amber-500 to-yellow-600",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "linear-gradient(135deg, rgba(245,158,11,0.15), rgba(234,179,8,0.1))",
        },
    },
    {
        id: "christmas_travel_1",
        name: "Christmas Getaway",
        category: "Festival",
        subcategory: "Christmas",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["christmas", "winter", "holiday", "getaway"],
        seasonalAvailability: ["christmas_2026"],
        palette: {
            bg: "bg-gradient-to-br from-red-700 to-green-800",
            text: "text-white",
            accent: "#dc2626",
            overlay: "linear-gradient(135deg, rgba(220,38,38,0.12), rgba(22,163,74,0.08))",
        },
    },
    {
        id: "christmas_package_2",
        name: "Xmas Package Deal",
        category: "Festival",
        subcategory: "Christmas",
        layout: "SplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["christmas", "package", "family"],
        seasonalAvailability: ["christmas_2026"],
        palette: {
            bg: "bg-gradient-to-br from-red-700 to-green-800",
            text: "text-white",
            accent: "#dc2626",
            overlay: "linear-gradient(135deg, rgba(220,38,38,0.12), rgba(22,163,74,0.08))",
        },
    },
    {
        id: "navratri_special_1",
        name: "Navratri Package",
        category: "Festival",
        subcategory: "Navratri",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["navratri", "garba", "gujarat", "festival"],
        seasonalAvailability: ["navratri_2026"],
        palette: {
            bg: "bg-gradient-to-br from-orange-500 to-red-600",
            text: "text-white",
            accent: "#ea580c",
            overlay: "linear-gradient(135deg, rgba(234,88,12,0.15), rgba(220,38,38,0.1))",
        },
    },
    {
        id: "eid_mubarak_1",
        name: "Eid Mubarak Travel",
        category: "Festival",
        subcategory: "Eid",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["eid", "mubarak", "holiday", "tour"],
        palette: {
            bg: "bg-gradient-to-br from-emerald-600 to-teal-700",
            text: "text-white",
            accent: "#059669",
            overlay: "linear-gradient(135deg, rgba(5,150,105,0.15), rgba(13,148,136,0.1))",
        },
    },
    {
        id: "independence_day_1",
        name: "Freedom Sale",
        category: "Festival",
        subcategory: "Independence Day",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["independence", "india", "sale", "tricolor"],
        seasonalAvailability: ["independence_day_2026"],
        palette: {
            bg: "bg-gradient-to-br from-orange-500 via-white to-green-600",
            text: "text-white",
            accent: "#ea580c",
            overlay: "linear-gradient(135deg, rgba(234,88,12,0.1), rgba(22,163,74,0.08))",
        },
    },
    {
        id: "new_year_1",
        name: "New Year Escape",
        category: "Festival",
        subcategory: "New Year",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["new year", "celebration", "travel", "2027"],
        palette: {
            bg: "bg-gradient-to-br from-violet-600 to-indigo-900",
            text: "text-white",
            accent: "#8b5cf6",
            overlay: "linear-gradient(135deg, rgba(139,92,246,0.15), rgba(67,56,202,0.1))",
        },
    },
    // Duotone Diwali
    {
        id: "duotone_diwali",
        name: "Diwali Duotone",
        category: "Festival",
        subcategory: "Diwali",
        layout: "DuotoneLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["diwali", "duotone", "festival", "modern"],
        seasonalAvailability: ["diwali_2026"],
    },
    // Banner Ribbon — Festival
    {
        id: "banner_festival_special",
        name: "Festival Banner Ribbon",
        category: "Festival",
        layout: "BannerRibbonLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["festival", "banner", "premium", "diwali", "holi", "christmas", "sale"],
        isMultiImage: true,
        imageSlotCount: 2,
        palette: {
            bg: "bg-gradient-to-r from-cyan-700 to-orange-500",
            text: "text-white",
            accent: "#f97316",
            overlay: "",
        },
    },
];
