import { SocialTemplate } from './types';

/** Package Type templates — Honeymoon, Family, Adventure, Luxury, Corporate */
export const packageTemplates: SocialTemplate[] = [
    {
        id: "honeymoon_paradise",
        name: "Honeymoon Paradise",
        category: "Package Type",
        subcategory: "Honeymoon",
        layout: "CenterLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["maldives", "honeymoon", "romantic", "couples"],
        palette: {
            bg: "bg-gradient-to-br from-pink-400 to-rose-600",
            text: "text-white",
            accent: "#ec4899",
            overlay: "linear-gradient(135deg, rgba(236,72,153,0.15), rgba(225,29,72,0.1))",
        },
    },
    {
        id: "honeymoon_europe",
        name: "Romantic Europe",
        category: "Package Type",
        subcategory: "Honeymoon",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["europe", "honeymoon", "paris", "romantic"],
        palette: {
            bg: "bg-gradient-to-br from-pink-400 to-rose-600",
            text: "text-white",
            accent: "#ec4899",
            overlay: "linear-gradient(135deg, rgba(236,72,153,0.15), rgba(225,29,72,0.1))",
        },
    },
    {
        id: "family_fun_1",
        name: "Family Fun Pack",
        category: "Package Type",
        subcategory: "Family",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["family", "kids", "fun", "vacation"],
        palette: {
            bg: "bg-gradient-to-br from-sky-400 to-blue-500",
            text: "text-white",
            accent: "#0ea5e9",
            overlay: "linear-gradient(135deg, rgba(14,165,233,0.12), rgba(59,130,246,0.08))",
        },
    },
    {
        id: "adventure_trip_1",
        name: "Adventure Awaits",
        category: "Package Type",
        subcategory: "Adventure",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["adventure", "trek", "camping", "mountains"],
        palette: {
            bg: "bg-gradient-to-br from-emerald-500 to-green-700",
            text: "text-white",
            accent: "#10b981",
            overlay: "linear-gradient(135deg, rgba(16,185,129,0.15), rgba(21,128,61,0.1))",
        },
    },
    {
        id: "luxury_escape_1",
        name: "Luxury Escape",
        category: "Package Type",
        subcategory: "Luxury",
        layout: "ElegantLayout",
        tier: "Business",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["luxury", "premium", "5star", "exclusive"],
        palette: {
            bg: "bg-gradient-to-br from-amber-600 to-yellow-800",
            text: "text-white",
            accent: "#d4a017",
            overlay: "linear-gradient(135deg, rgba(212,160,23,0.15), rgba(161,98,7,0.1))",
        },
    },
    {
        id: "corporate_travel_1",
        name: "Corporate Travel",
        category: "Package Type",
        subcategory: "Corporate",
        layout: "SplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["corporate", "business", "mice", "conference"],
        palette: {
            bg: "bg-gradient-to-br from-slate-700 to-blue-900",
            text: "text-white",
            accent: "#3b82f6",
            overlay: "linear-gradient(135deg, rgba(59,130,246,0.12), rgba(30,58,138,0.08))",
        },
    },
    // Service Showcase — Holiday Packages
    {
        id: "service_holidays_showcase",
        name: "Holiday Packages Showcase",
        category: "Package Type",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["holidays", "packages", "tour", "service", "booking"],
        defaultText: {
            headline: "Holiday Packages",
            subheadline: "Tailored Tours for Every Budget",
        },
    },
    // Info Split — Holiday Deal
    {
        id: "info_holiday_split",
        name: "Holiday Deal Split",
        category: "Package Type",
        layout: "InfoSplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holiday", "deal", "package", "split", "offer"],
        defaultText: {
            headline: "Holiday Deal",
            subheadline: "Fly, Stay & Tour — All Included",
        },
    },
    // Diagonal Split — Package Types
    {
        id: "diagonal_honeymoon",
        name: "Honeymoon Diagonal",
        category: "Package Type",
        subcategory: "Honeymoon",
        layout: "DiagonalSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["honeymoon", "romantic", "diagonal", "couples"],
    },
    {
        id: "diagonal_adventure",
        name: "Adventure Split",
        category: "Package Type",
        subcategory: "Adventure",
        layout: "DiagonalSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["adventure", "diagonal", "trek", "mountains", "dynamic"],
    },
    // Bold Typography — Corporate
    {
        id: "bold_type_corporate",
        name: "Corporate Bold",
        category: "Package Type",
        subcategory: "Corporate",
        layout: "BoldTypographyLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["corporate", "bold", "typography", "business", "professional"],
    },
    // Multi-image — Package Types
    {
        id: "multi-honeymoon-paradise-sq",
        name: "Honeymoon Paradise",
        category: "Package Type",
        layout: "WindowGalleryLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["honeymoon", "romantic", "couples", "paradise", "multi-image", "gallery"],
        isMultiImage: true,
        imageSlotCount: 3,
        defaultText: {
            destination: "Paradise Island",
            price: "\u20B91,19,999",
            offer: "Romantic Getaway",
        },
        palette: {
            bg: "linear-gradient(135deg, #9f1239, #ec4899)",
            text: "text-white",
            accent: "#ec4899",
            overlay: "linear-gradient(to top, rgba(136,19,55,0.95) 0%, rgba(136,19,55,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-family-getaway-sq",
        name: "Family Getaway",
        category: "Package Type",
        layout: "TriPanelLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["family", "kids", "vacation", "fun", "multi-image", "triptych"],
        isMultiImage: true,
        imageSlotCount: 3,
        defaultText: {
            destination: "Family Destinations",
            price: "\u20B944,999",
            offer: "Kids Stay Free",
        },
        palette: {
            bg: "linear-gradient(135deg, #0369a1, #0ea5e9)",
            text: "text-white",
            accent: "#0ea5e9",
            overlay: "linear-gradient(to top, rgba(12,74,110,0.95) 0%, rgba(12,74,110,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-adventure-collection-sq",
        name: "Adventure Collection",
        category: "Package Type",
        layout: "PolaroidScatterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["adventure", "trek", "outdoor", "extreme", "multi-image", "polaroid"],
        isMultiImage: true,
        imageSlotCount: 3,
        defaultText: {
            destination: "Adventure Spots",
            price: "\u20B939,999",
            offer: "Thrill Seeker Package",
        },
        palette: {
            bg: "linear-gradient(135deg, #991b1b, #ef4444)",
            text: "text-white",
            accent: "#ef4444",
            overlay: "linear-gradient(to top, rgba(127,29,29,0.95) 0%, rgba(127,29,29,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-luxury-escape-sq",
        name: "Luxury Escape",
        category: "Package Type",
        layout: "WindowGalleryLayout",
        tier: "Business",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["luxury", "premium", "5star", "exclusive", "multi-image", "gallery"],
        isMultiImage: true,
        imageSlotCount: 3,
        defaultText: {
            destination: "Luxury Retreats",
            price: "\u20B92,99,999",
            offer: "Ultra-Premium Escape",
        },
        palette: {
            bg: "linear-gradient(135deg, #334155, #ca8a04)",
            text: "text-white",
            accent: "#ca8a04",
            overlay: "linear-gradient(to top, rgba(30,41,59,0.95) 0%, rgba(30,41,59,0.4) 50%, transparent 100%)",
        },
    },
];
