import { SocialTemplate } from './types';

/** Destination gallery templates — multi-image and premium composite layouts */
export const destinationGalleryTemplates: SocialTemplate[] = [
    // ─── MULTI-IMAGE DESTINATIONS ──────────────────────────────────────────────
    {
        id: "multi-maldives-showcase-sq",
        name: "Maldives Showcase",
        category: "Destination",
        layout: "CollageGridLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["maldives", "beach", "luxury", "multi-image", "collage"],
        isMultiImage: true,
        imageSlotCount: 4,
        defaultText: {
            destination: "Maldives",
            price: "\u20B989,999",
            offer: "All-Inclusive Package",
        },
        palette: {
            bg: "linear-gradient(135deg, #0f766e, #06b6d4)",
            text: "text-white",
            accent: "#06b6d4",
            overlay: "linear-gradient(to top, rgba(15,23,42,0.95) 0%, rgba(15,23,42,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-dubai-experience-sq",
        name: "Dubai Experience",
        category: "Destination",
        layout: "CollageGridLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["dubai", "luxury", "skyline", "multi-image", "collage"],
        isMultiImage: true,
        imageSlotCount: 4,
        defaultText: {
            destination: "Dubai",
            price: "\u20B91,29,999",
            offer: "Premium Experience",
        },
        palette: {
            bg: "linear-gradient(135deg, #b45309, #f59e0b)",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "linear-gradient(to top, rgba(120,53,15,0.95) 0%, rgba(120,53,15,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-bali-discovery-sq",
        name: "Bali Discovery",
        category: "Destination",
        layout: "TriPanelLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["bali", "tropical", "nature", "multi-image", "triptych"],
        isMultiImage: true,
        imageSlotCount: 3,
        defaultText: {
            destination: "Bali",
            price: "\u20B974,999",
            offer: "Island Discovery Tour",
        },
        palette: {
            bg: "linear-gradient(135deg, #065f46, #10b981)",
            text: "text-white",
            accent: "#10b981",
            overlay: "linear-gradient(to top, rgba(6,78,59,0.95) 0%, rgba(6,78,59,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-thailand-explorer-sq",
        name: "Thailand Explorer",
        category: "Destination",
        layout: "TriPanelLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["thailand", "asia", "adventure", "multi-image", "triptych"],
        isMultiImage: true,
        imageSlotCount: 3,
        defaultText: {
            destination: "Thailand",
            price: "\u20B959,999",
            offer: "Explorer Package",
        },
        palette: {
            bg: "linear-gradient(135deg, #c2410c, #f97316)",
            text: "text-white",
            accent: "#f97316",
            overlay: "linear-gradient(to top, rgba(124,45,18,0.95) 0%, rgba(124,45,18,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-kashmir-panorama-sq",
        name: "Kashmir Panorama",
        category: "Destination",
        layout: "MosaicStripLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["kashmir", "snow", "mountains", "panorama", "multi-image", "mosaic"],
        isMultiImage: true,
        imageSlotCount: 5,
        defaultText: {
            destination: "Kashmir",
            price: "\u20B969,999",
            offer: "Panoramic Tour",
        },
        palette: {
            bg: "linear-gradient(135deg, #334155, #3b82f6)",
            text: "text-white",
            accent: "#3b82f6",
            overlay: "linear-gradient(to top, rgba(30,41,59,0.95) 0%, rgba(30,41,59,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-kerala-backwaters-sq",
        name: "Kerala Backwaters",
        category: "Destination",
        layout: "MosaicStripLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["kerala", "backwaters", "nature", "houseboat", "multi-image", "mosaic"],
        isMultiImage: true,
        imageSlotCount: 5,
        defaultText: {
            destination: "Kerala",
            price: "\u20B954,999",
            offer: "Backwaters Cruise",
        },
        palette: {
            bg: "linear-gradient(135deg, #115e59, #14b8a6)",
            text: "text-white",
            accent: "#14b8a6",
            overlay: "linear-gradient(to top, rgba(19,78,74,0.95) 0%, rgba(19,78,74,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-rajasthan-heritage-sq",
        name: "Rajasthan Heritage",
        category: "Destination",
        layout: "CollageGridLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["rajasthan", "heritage", "palace", "culture", "multi-image", "collage"],
        isMultiImage: true,
        imageSlotCount: 4,
        defaultText: {
            destination: "Rajasthan",
            price: "\u20B949,999",
            offer: "Heritage Royal Tour",
        },
        palette: {
            bg: "linear-gradient(135deg, #9f1239, #f59e0b)",
            text: "text-white",
            accent: "#e11d48",
            overlay: "linear-gradient(to top, rgba(136,19,55,0.95) 0%, rgba(136,19,55,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-goa-vibes-sq",
        name: "Goa Vibes",
        category: "Destination",
        layout: "PolaroidScatterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["goa", "beach", "party", "vibes", "multi-image", "polaroid"],
        isMultiImage: true,
        imageSlotCount: 3,
        defaultText: {
            destination: "Goa",
            price: "\u20B929,999",
            offer: "Beach Vibes Package",
        },
        palette: {
            bg: "linear-gradient(135deg, #6d28d9, #ec4899)",
            text: "text-white",
            accent: "#8b5cf6",
            overlay: "linear-gradient(to top, rgba(88,28,135,0.95) 0%, rgba(88,28,135,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-europe-grand-tour-sq",
        name: "Europe Grand Tour",
        category: "Destination",
        layout: "MosaicStripLayout",
        tier: "Business",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["europe", "grand tour", "premium", "multi-city", "multi-image", "mosaic"],
        isMultiImage: true,
        imageSlotCount: 5,
        defaultText: {
            destination: "Europe",
            price: "\u20B92,49,999",
            offer: "Grand Tour — 5 Countries",
        },
        palette: {
            bg: "linear-gradient(135deg, #1e1b4b, #6366f1)",
            text: "text-white",
            accent: "#6366f1",
            overlay: "linear-gradient(to top, rgba(30,27,75,0.95) 0%, rgba(30,27,75,0.4) 50%, transparent 100%)",
        },
    },

    // ─── PREMIUM COMPOSITE — DESTINATION ───────────────────────────────────────
    // Wave Divider
    {
        id: "wave_beach_escape",
        name: "Wave Beach Escape",
        category: "Destination",
        subcategory: "Beach",
        layout: "WaveDividerLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["beach", "tropical", "wave", "premium", "maldives", "bali", "goa"],
        palette: {
            bg: "bg-white",
            text: "text-slate-800",
            accent: "#0891b2",
            overlay: "",
        },
    },
    {
        id: "wave_mountain_trek",
        name: "Mountain Wave Vista",
        category: "Destination",
        subcategory: "Mountain",
        layout: "WaveDividerLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1350 },
        aspectRatio: "portrait",
        colorScheme: "light",
        tags: ["mountain", "trek", "adventure", "premium", "kashmir", "manali", "himalayas"],
        palette: {
            bg: "bg-white",
            text: "text-slate-800",
            accent: "#059669",
            overlay: "",
        },
    },
    // Circle Accent
    {
        id: "circle_luxury_escape",
        name: "Luxury Circle Gallery",
        category: "Destination",
        subcategory: "Luxury",
        layout: "CircleAccentLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["luxury", "gallery", "circle", "premium", "honeymoon", "resort"],
        isMultiImage: true,
        imageSlotCount: 4,
        palette: {
            bg: "bg-white",
            text: "text-slate-800",
            accent: "#d97706",
            overlay: "",
        },
    },
    {
        id: "circle_cultural_journey",
        name: "Cultural Circle Tour",
        category: "Destination",
        subcategory: "Culture",
        layout: "CircleAccentLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1350 },
        aspectRatio: "portrait",
        colorScheme: "light",
        tags: ["culture", "heritage", "tour", "premium", "rajasthan", "temple", "india"],
        isMultiImage: true,
        imageSlotCount: 4,
        palette: {
            bg: "bg-white",
            text: "text-slate-800",
            accent: "#b45309",
            overlay: "",
        },
    },
    // Floating Card
    {
        id: "floating_romantic_getaway",
        name: "Romantic Floating Card",
        category: "Destination",
        subcategory: "Romance",
        layout: "FloatingCardLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["romance", "honeymoon", "luxury", "premium", "couple", "paris", "santorini"],
        palette: {
            bg: "bg-slate-900",
            text: "text-white",
            accent: "#e11d48",
            overlay: "linear-gradient(to top, rgba(15,23,42,0.9) 0%, rgba(15,23,42,0.3) 50%, transparent 100%)",
        },
    },
    {
        id: "floating_adventure_card",
        name: "Adventure Floating Card",
        category: "Destination",
        subcategory: "Adventure",
        layout: "FloatingCardLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1920 },
        aspectRatio: "story",
        colorScheme: "dark",
        tags: ["adventure", "trekking", "safari", "premium", "wildlife", "exploration"],
        palette: {
            bg: "bg-slate-900",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "linear-gradient(to top, rgba(15,23,42,0.9) 0%, rgba(15,23,42,0.3) 50%, transparent 100%)",
        },
    },
    // Premium Collage
    {
        id: "collage_premium_explorer",
        name: "Premium Explorer Collage",
        category: "Destination",
        layout: "PremiumCollageLayout",
        tier: "Business",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["collage", "gallery", "premium", "explorer", "multi-destination"],
        isMultiImage: true,
        imageSlotCount: 4,
        palette: {
            bg: "bg-gradient-to-br from-cyan-700 to-teal-800",
            text: "text-white",
            accent: "#f97316",
            overlay: "",
        },
    },
    {
        id: "collage_luxury_retreat",
        name: "Luxury Retreat Collage",
        category: "Destination",
        subcategory: "Luxury",
        layout: "PremiumCollageLayout",
        tier: "Business",
        dimensions: { width: 1080, height: 1350 },
        aspectRatio: "portrait",
        colorScheme: "brand",
        tags: ["luxury", "retreat", "spa", "premium", "collage", "resort"],
        isMultiImage: true,
        imageSlotCount: 4,
        palette: {
            bg: "bg-gradient-to-br from-purple-800 to-indigo-900",
            text: "text-white",
            accent: "#fbbf24",
            overlay: "",
        },
    },
    // Split Wave
    {
        id: "split_wave_dubai_luxury",
        name: "Dubai Split Wave",
        category: "Destination",
        subcategory: "Dubai",
        layout: "SplitWaveLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["dubai", "luxury", "split", "premium", "uae", "abu dhabi"],
        palette: {
            bg: "bg-gradient-to-b from-cyan-700 to-cyan-900",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "",
        },
    },
    {
        id: "split_wave_europe_tour",
        name: "Europe Split Wave",
        category: "Destination",
        subcategory: "Europe",
        layout: "SplitWaveLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1350 },
        aspectRatio: "portrait",
        colorScheme: "brand",
        tags: ["europe", "tour", "split", "premium", "paris", "london", "rome"],
        palette: {
            bg: "bg-gradient-to-b from-indigo-700 to-violet-800",
            text: "text-white",
            accent: "#fb923c",
            overlay: "",
        },
    },
];
