import { SocialTemplate } from './types';

/** Promotion templates — Flash Sale, Early Bird, Group Discount, Last Minute */
export const promotionTemplates: SocialTemplate[] = [
    {
        id: "flash_sale_1",
        name: "Flash Sale 48Hr",
        category: "Promotion",
        subcategory: "Flash Sale",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["flash sale", "urgent", "48hr", "deal"],
        palette: {
            bg: "bg-gradient-to-br from-red-500 to-rose-600",
            text: "text-white",
            accent: "#ef4444",
            overlay: "linear-gradient(135deg, rgba(239,68,68,0.15), rgba(225,29,72,0.1))",
        },
    },
    {
        id: "early_bird_1",
        name: "Early Bird Offer",
        category: "Promotion",
        subcategory: "Early Bird",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["early bird", "book now", "save", "advance"],
        palette: {
            bg: "bg-gradient-to-br from-teal-500 to-cyan-600",
            text: "text-white",
            accent: "#14b8a6",
            overlay: "linear-gradient(135deg, rgba(20,184,166,0.12), rgba(6,182,212,0.08))",
        },
    },
    {
        id: "group_discount_1",
        name: "Group Discount",
        category: "Promotion",
        subcategory: "Group",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["group", "discount", "10+", "friends"],
        palette: {
            bg: "bg-gradient-to-br from-violet-500 to-purple-700",
            text: "text-white",
            accent: "#8b5cf6",
            overlay: "linear-gradient(135deg, rgba(139,92,246,0.15), rgba(126,34,206,0.1))",
        },
    },
    {
        id: "last_minute_1",
        name: "Last Minute Deal",
        category: "Promotion",
        subcategory: "Last Minute",
        layout: "CenterLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["last minute", "deal", "urgent", "limited"],
        palette: {
            bg: "bg-gradient-to-br from-orange-500 to-red-600",
            text: "text-white",
            accent: "#f97316",
            overlay: "linear-gradient(135deg, rgba(249,115,22,0.15), rgba(220,38,38,0.1))",
        },
    },
    // Gradient Hero — Flash Sale
    {
        id: "gradient_hero_flash",
        name: "Cinematic Flash Sale",
        category: "Promotion",
        subcategory: "Flash Sale",
        layout: "GradientHeroLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["flash sale", "cinematic", "urgent", "promotion"],
    },
    // Magazine Cover — Early Bird
    {
        id: "magazine_early_bird",
        name: "Early Bird Editorial",
        category: "Promotion",
        subcategory: "Early Bird",
        layout: "MagazineCoverLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["early bird", "editorial", "elegant", "promotion"],
    },
    // Bold Typography — Group Booking
    {
        id: "bold_type_group",
        name: "Group Booking Bold",
        category: "Promotion",
        subcategory: "Group",
        layout: "BoldTypographyLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["group", "bold", "typography", "promotion", "booking"],
    },
    // Info Split — Group Booking
    {
        id: "info_group_booking",
        name: "Group Booking Offer",
        category: "Promotion",
        layout: "InfoSplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["group", "booking", "offer", "corporate", "discount"],
        defaultText: {
            headline: "Group Booking Offer",
            subheadline: "Book 10+ Get Special Rates",
        },
    },
];
