import { SocialTemplate } from './types';

/** Content templates — Review, Carousel, Informational, Service Showcase */
export const contentTemplates: SocialTemplate[] = [
    // ─── REVIEW ────────────────────────────────────────────────────────────────
    {
        id: "review_stars_minimal",
        name: "Minimalist Stars Review",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["review", "customer love", "5star"],
    },
    {
        id: "review_dark_quote",
        name: "Dark Quote Card",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["review", "quote", "testimonial", "dark"],
    },
    {
        id: "review_elegant_1",
        name: "Elegant Testimonial",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["review", "elegant", "branded", "testimonial"],
    },

    // ─── CAROUSEL ──────────────────────────────────────────────────────────────
    {
        id: "trip_highlights_carousel",
        name: "Trip Highlights",
        category: "Carousel",
        layout: "CarouselSlideLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["carousel", "highlights", "photos", "trip"],
        isCarousel: true,
        palette: {
            bg: "bg-gradient-to-br from-amber-100 to-orange-100",
            text: "text-slate-800",
            accent: "#c4956a",
            overlay: "linear-gradient(135deg, rgba(196,149,106,0.1), rgba(139,115,85,0.08))",
        },
    },
    {
        id: "day_by_day_carousel",
        name: "Day-by-Day Itinerary",
        category: "Carousel",
        layout: "CarouselSlideLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["carousel", "itinerary", "day by day", "trip"],
        isCarousel: true,
        palette: {
            bg: "bg-gradient-to-br from-stone-200 to-amber-100",
            text: "text-slate-800",
            accent: "#8b7355",
            overlay: "linear-gradient(135deg, rgba(139,115,85,0.12), rgba(196,149,106,0.08))",
        },
    },

    // ─── INFORMATIONAL ─────────────────────────────────────────────────────────
    {
        id: "services_overview",
        name: "Our Services",
        category: "Informational",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["services", "about", "what we offer"],
        palette: {
            bg: "bg-gradient-to-br from-slate-600 to-slate-800",
            text: "text-white",
            accent: "#3b82f6",
            overlay: "linear-gradient(135deg, rgba(59,130,246,0.1), rgba(51,65,85,0.08))",
        },
    },
    {
        id: "why_choose_us",
        name: "Why Choose Us",
        category: "Informational",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["trust", "why us", "agency", "benefits"],
        palette: {
            bg: "bg-gradient-to-br from-blue-50 to-indigo-100",
            text: "text-slate-900",
            accent: "#4f46e5",
            overlay: "linear-gradient(135deg, rgba(79,70,229,0.08), rgba(99,102,241,0.05))",
        },
    },

    // ─── SERVICE SHOWCASE ──────────────────────────────────────────────────────
    {
        id: "service_car_luxury",
        name: "Luxury Car Service",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["car", "luxury", "transfer", "airport", "service"],
        defaultText: {
            headline: "Luxury Car Service",
            subheadline: "Comfort & Style on Every Ride",
        },
    },
    {
        id: "service_visa_showcase",
        name: "Visa Services Card",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["visa", "services", "documentation", "passport", "apply"],
        defaultText: {
            headline: "Visa Services",
            subheadline: "Hassle-Free Visa Processing",
        },
    },
    {
        id: "service_airport_transfers",
        name: "Airport Transfers",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["airport", "transfer", "pickup", "drop", "car"],
        defaultText: {
            headline: "Airport Transfers",
            subheadline: "On-Time, Every Time",
        },
    },

    // ─── INFO SPLIT ────────────────────────────────────────────────────────────
    {
        id: "info_visa_split",
        name: "Get Your Visa Now",
        category: "Informational",
        layout: "InfoSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["visa", "apply", "now", "documentation", "international"],
        defaultText: {
            headline: "Get Your Visa Now",
            subheadline: "Fast • Reliable • Affordable",
        },
    },
];
