import { SocialTemplate } from './types';

export const templates: SocialTemplate[] = [
    // ─── FESTIVAL ───────────────────────────────────────────────────────────────
    {
        id: "holi_special_1",
        name: "Festival of Colors",
        category: "Festival",
        subcategory: "Holi",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holi", "colors", "offer", "spring"],
        seasonalAvailability: ["holi_2026"],
        defaultText: {
            headline: "Happy Holi!",
            subheadline: "May your life be filled with vibrant colors",
            body: "Special 20% off on all domestic packages this Holi."
        },
        palette: {
            bg: "bg-gradient-to-br from-rose-500 to-orange-500",
            text: "text-white",
            accent: "#ff6b6b",
            overlay: "linear-gradient(135deg, rgba(255,107,107,0.15), rgba(255,140,66,0.1))",
        },
    },
    {
        id: "holi_special_2",
        name: "Holi Splash Sale",
        category: "Festival",
        subcategory: "Holi",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holi", "sale", "festival"],
        seasonalAvailability: ["holi_2026"],
        palette: {
            bg: "bg-gradient-to-br from-rose-500 to-orange-500",
            text: "text-white",
            accent: "#ff6b6b",
            overlay: "linear-gradient(135deg, rgba(255,107,107,0.15), rgba(255,140,66,0.1))",
        },
    },
    {
        id: "diwali_grand_offer",
        name: "Diwali Grand Sale",
        category: "Festival",
        subcategory: "Diwali",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["diwali", "sale", "festive"],
        seasonalAvailability: ["diwali_2026"],
        palette: {
            bg: "bg-gradient-to-br from-amber-500 to-yellow-600",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "linear-gradient(135deg, rgba(245,158,11,0.15), rgba(234,179,8,0.1))",
        },
    },
    {
        id: "diwali_lights_2",
        name: "Diwali Glow",
        category: "Festival",
        subcategory: "Diwali",
        layout: "BottomLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["diwali", "lights", "luxury"],
        seasonalAvailability: ["diwali_2026"],
        palette: {
            bg: "bg-gradient-to-br from-amber-500 to-yellow-600",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "linear-gradient(135deg, rgba(245,158,11,0.15), rgba(234,179,8,0.1))",
        },
    },
    {
        id: "christmas_travel_1",
        name: "Christmas Getaway",
        category: "Festival",
        subcategory: "Christmas",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["christmas", "winter", "holiday", "getaway"],
        seasonalAvailability: ["christmas_2026"],
        palette: {
            bg: "bg-gradient-to-br from-red-700 to-green-800",
            text: "text-white",
            accent: "#dc2626",
            overlay: "linear-gradient(135deg, rgba(220,38,38,0.12), rgba(22,163,74,0.08))",
        },
    },
    {
        id: "christmas_package_2",
        name: "Xmas Package Deal",
        category: "Festival",
        subcategory: "Christmas",
        layout: "SplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["christmas", "package", "family"],
        seasonalAvailability: ["christmas_2026"],
        palette: {
            bg: "bg-gradient-to-br from-red-700 to-green-800",
            text: "text-white",
            accent: "#dc2626",
            overlay: "linear-gradient(135deg, rgba(220,38,38,0.12), rgba(22,163,74,0.08))",
        },
    },
    {
        id: "navratri_special_1",
        name: "Navratri Package",
        category: "Festival",
        subcategory: "Navratri",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["navratri", "garba", "gujarat", "festival"],
        seasonalAvailability: ["navratri_2026"],
        palette: {
            bg: "bg-gradient-to-br from-orange-500 to-red-600",
            text: "text-white",
            accent: "#ea580c",
            overlay: "linear-gradient(135deg, rgba(234,88,12,0.15), rgba(220,38,38,0.1))",
        },
    },
    {
        id: "eid_mubarak_1",
        name: "Eid Mubarak Travel",
        category: "Festival",
        subcategory: "Eid",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["eid", "mubarak", "holiday", "tour"],
        palette: {
            bg: "bg-gradient-to-br from-emerald-600 to-teal-700",
            text: "text-white",
            accent: "#059669",
            overlay: "linear-gradient(135deg, rgba(5,150,105,0.15), rgba(13,148,136,0.1))",
        },
    },
    {
        id: "independence_day_1",
        name: "Freedom Sale",
        category: "Festival",
        subcategory: "Independence Day",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["independence", "india", "sale", "tricolor"],
        seasonalAvailability: ["independence_day_2026"],
        palette: {
            bg: "bg-gradient-to-br from-orange-500 via-white to-green-600",
            text: "text-white",
            accent: "#ea580c",
            overlay: "linear-gradient(135deg, rgba(234,88,12,0.1), rgba(22,163,74,0.08))",
        },
    },
    {
        id: "new_year_1",
        name: "New Year Escape",
        category: "Festival",
        subcategory: "New Year",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["new year", "celebration", "travel", "2027"],
        palette: {
            bg: "bg-gradient-to-br from-violet-600 to-indigo-900",
            text: "text-white",
            accent: "#8b5cf6",
            overlay: "linear-gradient(135deg, rgba(139,92,246,0.15), rgba(67,56,202,0.1))",
        },
    },

    // ─── SEASON ─────────────────────────────────────────────────────────────────
    {
        id: "summer_beach_1",
        name: "Summer Beach Escape",
        category: "Season",
        subcategory: "Summer",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["summer", "beach", "escape", "hot"],
        palette: {
            bg: "bg-gradient-to-br from-cyan-400 to-blue-500",
            text: "text-white",
            accent: "#06b6d4",
            overlay: "linear-gradient(135deg, rgba(6,182,212,0.15), rgba(59,130,246,0.1))",
        },
    },
    {
        id: "summer_special_2",
        name: "Hot Summer Deals",
        category: "Season",
        subcategory: "Summer",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["summer", "deal", "sale", "vacation"],
        palette: {
            bg: "bg-gradient-to-br from-cyan-400 to-blue-500",
            text: "text-white",
            accent: "#06b6d4",
            overlay: "linear-gradient(135deg, rgba(6,182,212,0.15), rgba(59,130,246,0.1))",
        },
    },
    {
        id: "monsoon_magic_1",
        name: "Monsoon Magic",
        category: "Season",
        subcategory: "Monsoon",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["monsoon", "rain", "kerala", "nature"],
        palette: {
            bg: "bg-gradient-to-br from-slate-700 to-emerald-800",
            text: "text-white",
            accent: "#10b981",
            overlay: "linear-gradient(135deg, rgba(16,185,129,0.15), rgba(51,65,85,0.1))",
        },
    },
    {
        id: "winter_hills_1",
        name: "Winter Hills Special",
        category: "Season",
        subcategory: "Winter",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["winter", "snow", "manali", "hills"],
        palette: {
            bg: "bg-gradient-to-br from-indigo-400 to-blue-800",
            text: "text-white",
            accent: "#818cf8",
            overlay: "linear-gradient(135deg, rgba(129,140,248,0.15), rgba(30,64,175,0.1))",
        },
    },

    // ─── DESTINATION ────────────────────────────────────────────────────────────
    {
        id: "destination_dubai_1",
        name: "Dubai Skyline",
        category: "Destination",
        subcategory: "Dubai",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["dubai", "uae", "luxury", "burj"],
        palette: {
            bg: "bg-gradient-to-br from-amber-600 to-yellow-800",
            text: "text-white",
            accent: "#d4a017",
            overlay: "linear-gradient(135deg, rgba(212,160,23,0.15), rgba(161,98,7,0.1))",
        },
    },
    {
        id: "destination_bali_1",
        name: "Bali Paradise",
        category: "Destination",
        subcategory: "Bali",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["bali", "indonesia", "paradise", "tropical"],
        palette: {
            bg: "bg-gradient-to-br from-emerald-500 to-teal-600",
            text: "text-white",
            accent: "#10b981",
            overlay: "linear-gradient(135deg, rgba(16,185,129,0.15), rgba(13,148,136,0.1))",
        },
    },
    {
        id: "destination_maldives_1",
        name: "Maldives Luxury",
        category: "Destination",
        subcategory: "Maldives",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["maldives", "luxury", "overwater", "island"],
        palette: {
            bg: "bg-gradient-to-br from-cyan-400 to-blue-600",
            text: "text-white",
            accent: "#06b6d4",
            overlay: "linear-gradient(135deg, rgba(6,182,212,0.15), rgba(37,99,235,0.1))",
        },
    },
    {
        id: "destination_kashmir_1",
        name: "Kashmir Valley",
        category: "Destination",
        subcategory: "Kashmir",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["kashmir", "valley", "snow", "paradise"],
        palette: {
            bg: "bg-gradient-to-br from-slate-600 to-blue-900",
            text: "text-white",
            accent: "#60a5fa",
            overlay: "linear-gradient(135deg, rgba(96,165,250,0.12), rgba(30,58,138,0.1))",
        },
    },
    {
        id: "destination_europe_1",
        name: "Europe Explorer",
        category: "Destination",
        subcategory: "Europe",
        layout: "BottomLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["europe", "paris", "rome", "travel"],
        palette: {
            bg: "bg-gradient-to-br from-blue-500 to-indigo-700",
            text: "text-white",
            accent: "#3b82f6",
            overlay: "linear-gradient(135deg, rgba(59,130,246,0.15), rgba(67,56,202,0.1))",
        },
    },
    {
        id: "destination_thailand_1",
        name: "Thailand Adventure",
        category: "Destination",
        subcategory: "Thailand",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["thailand", "bangkok", "phuket", "asia"],
        palette: {
            bg: "bg-gradient-to-br from-amber-500 to-orange-600",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "linear-gradient(135deg, rgba(245,158,11,0.12), rgba(234,88,12,0.08))",
        },
    },
    {
        id: "destination_kerala_1",
        name: "God's Own Country",
        category: "Destination",
        subcategory: "Kerala",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["kerala", "backwaters", "ayurveda", "india"],
        palette: {
            bg: "bg-gradient-to-br from-green-500 to-emerald-700",
            text: "text-white",
            accent: "#22c55e",
            overlay: "linear-gradient(135deg, rgba(34,197,94,0.15), rgba(4,120,87,0.1))",
        },
    },

    // ─── PACKAGE TYPE ────────────────────────────────────────────────────────────
    {
        id: "honeymoon_paradise",
        name: "Honeymoon Paradise",
        category: "Package Type",
        subcategory: "Honeymoon",
        layout: "CenterLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["maldives", "honeymoon", "romantic", "couples"],
        palette: {
            bg: "bg-gradient-to-br from-pink-400 to-rose-600",
            text: "text-white",
            accent: "#ec4899",
            overlay: "linear-gradient(135deg, rgba(236,72,153,0.15), rgba(225,29,72,0.1))",
        },
    },
    {
        id: "honeymoon_europe",
        name: "Romantic Europe",
        category: "Package Type",
        subcategory: "Honeymoon",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["europe", "honeymoon", "paris", "romantic"],
        palette: {
            bg: "bg-gradient-to-br from-pink-400 to-rose-600",
            text: "text-white",
            accent: "#ec4899",
            overlay: "linear-gradient(135deg, rgba(236,72,153,0.15), rgba(225,29,72,0.1))",
        },
    },
    {
        id: "family_fun_1",
        name: "Family Fun Pack",
        category: "Package Type",
        subcategory: "Family",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["family", "kids", "fun", "vacation"],
        palette: {
            bg: "bg-gradient-to-br from-sky-400 to-blue-500",
            text: "text-white",
            accent: "#0ea5e9",
            overlay: "linear-gradient(135deg, rgba(14,165,233,0.12), rgba(59,130,246,0.08))",
        },
    },
    {
        id: "adventure_trip_1",
        name: "Adventure Awaits",
        category: "Package Type",
        subcategory: "Adventure",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["adventure", "trek", "camping", "mountains"],
        palette: {
            bg: "bg-gradient-to-br from-emerald-500 to-green-700",
            text: "text-white",
            accent: "#10b981",
            overlay: "linear-gradient(135deg, rgba(16,185,129,0.15), rgba(21,128,61,0.1))",
        },
    },
    {
        id: "luxury_escape_1",
        name: "Luxury Escape",
        category: "Package Type",
        subcategory: "Luxury",
        layout: "ElegantLayout",
        tier: "Business",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["luxury", "premium", "5star", "exclusive"],
        palette: {
            bg: "bg-gradient-to-br from-amber-600 to-yellow-800",
            text: "text-white",
            accent: "#d4a017",
            overlay: "linear-gradient(135deg, rgba(212,160,23,0.15), rgba(161,98,7,0.1))",
        },
    },
    {
        id: "corporate_travel_1",
        name: "Corporate Travel",
        category: "Package Type",
        subcategory: "Corporate",
        layout: "SplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["corporate", "business", "mice", "conference"],
        palette: {
            bg: "bg-gradient-to-br from-slate-700 to-blue-900",
            text: "text-white",
            accent: "#3b82f6",
            overlay: "linear-gradient(135deg, rgba(59,130,246,0.12), rgba(30,58,138,0.08))",
        },
    },

    // ─── PROMOTION ───────────────────────────────────────────────────────────────
    {
        id: "flash_sale_1",
        name: "Flash Sale 48Hr",
        category: "Promotion",
        subcategory: "Flash Sale",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["flash sale", "urgent", "48hr", "deal"],
        palette: {
            bg: "bg-gradient-to-br from-red-500 to-rose-600",
            text: "text-white",
            accent: "#ef4444",
            overlay: "linear-gradient(135deg, rgba(239,68,68,0.15), rgba(225,29,72,0.1))",
        },
    },
    {
        id: "early_bird_1",
        name: "Early Bird Offer",
        category: "Promotion",
        subcategory: "Early Bird",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["early bird", "book now", "save", "advance"],
        palette: {
            bg: "bg-gradient-to-br from-teal-500 to-cyan-600",
            text: "text-white",
            accent: "#14b8a6",
            overlay: "linear-gradient(135deg, rgba(20,184,166,0.12), rgba(6,182,212,0.08))",
        },
    },
    {
        id: "group_discount_1",
        name: "Group Discount",
        category: "Promotion",
        subcategory: "Group",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["group", "discount", "10+", "friends"],
        palette: {
            bg: "bg-gradient-to-br from-violet-500 to-purple-700",
            text: "text-white",
            accent: "#8b5cf6",
            overlay: "linear-gradient(135deg, rgba(139,92,246,0.15), rgba(126,34,206,0.1))",
        },
    },
    {
        id: "last_minute_1",
        name: "Last Minute Deal",
        category: "Promotion",
        subcategory: "Last Minute",
        layout: "CenterLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["last minute", "deal", "urgent", "limited"],
        palette: {
            bg: "bg-gradient-to-br from-orange-500 to-red-600",
            text: "text-white",
            accent: "#f97316",
            overlay: "linear-gradient(135deg, rgba(249,115,22,0.15), rgba(220,38,38,0.1))",
        },
    },

    // ─── REVIEW ──────────────────────────────────────────────────────────────────
    {
        id: "review_stars_minimal",
        name: "Minimalist Stars Review",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["review", "customer love", "5star"],
    },
    {
        id: "review_dark_quote",
        name: "Dark Quote Card",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["review", "quote", "testimonial", "dark"],
    },
    {
        id: "review_elegant_1",
        name: "Elegant Testimonial",
        category: "Review",
        layout: "ReviewLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["review", "elegant", "branded", "testimonial"],
    },

    // ─── CAROUSEL ────────────────────────────────────────────────────────────────
    {
        id: "trip_highlights_carousel",
        name: "Trip Highlights",
        category: "Carousel",
        layout: "CarouselSlideLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["carousel", "highlights", "photos", "trip"],
        isCarousel: true,
        palette: {
            bg: "bg-gradient-to-br from-amber-100 to-orange-100",
            text: "text-slate-800",
            accent: "#c4956a",
            overlay: "linear-gradient(135deg, rgba(196,149,106,0.1), rgba(139,115,85,0.08))",
        },
    },
    {
        id: "day_by_day_carousel",
        name: "Day-by-Day Itinerary",
        category: "Carousel",
        layout: "CarouselSlideLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["carousel", "itinerary", "day by day", "trip"],
        isCarousel: true,
        palette: {
            bg: "bg-gradient-to-br from-stone-200 to-amber-100",
            text: "text-slate-800",
            accent: "#8b7355",
            overlay: "linear-gradient(135deg, rgba(139,115,85,0.12), rgba(196,149,106,0.08))",
        },
    },

    // ─── INFORMATIONAL ───────────────────────────────────────────────────────────
    {
        id: "services_overview",
        name: "Our Services",
        category: "Informational",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["services", "about", "what we offer"],
        palette: {
            bg: "bg-gradient-to-br from-slate-600 to-slate-800",
            text: "text-white",
            accent: "#3b82f6",
            overlay: "linear-gradient(135deg, rgba(59,130,246,0.1), rgba(51,65,85,0.08))",
        },
    },
    {
        id: "why_choose_us",
        name: "Why Choose Us",
        category: "Informational",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["trust", "why us", "agency", "benefits"],
        palette: {
            bg: "bg-gradient-to-br from-blue-50 to-indigo-100",
            text: "text-slate-900",
            accent: "#4f46e5",
            overlay: "linear-gradient(135deg, rgba(79,70,229,0.08), rgba(99,102,241,0.05))",
        },
    },

    // ─── SERVICE SHOWCASE (real poster format) ───────────────────────────────────
    {
        id: "service_car_luxury",
        name: "Luxury Car Service",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["car", "luxury", "transfer", "airport", "service"],
        defaultText: {
            headline: "Luxury Car Service",
            subheadline: "Comfort & Style on Every Ride",
        },
    },
    {
        id: "service_holidays_showcase",
        name: "Holiday Packages Showcase",
        category: "Package Type",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["holidays", "packages", "tour", "service", "booking"],
        defaultText: {
            headline: "Holiday Packages",
            subheadline: "Tailored Tours for Every Budget",
        },
    },
    {
        id: "service_visa_showcase",
        name: "Visa Services Card",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["visa", "services", "documentation", "passport", "apply"],
        defaultText: {
            headline: "Visa Services",
            subheadline: "Hassle-Free Visa Processing",
        },
    },
    {
        id: "service_airport_transfers",
        name: "Airport Transfers",
        category: "Informational",
        layout: "ServiceShowcaseLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["airport", "transfer", "pickup", "drop", "car"],
        defaultText: {
            headline: "Airport Transfers",
            subheadline: "On-Time, Every Time",
        },
    },

    // ─── HERO SERVICES (real poster format) ─────────────────────────────────────
    {
        id: "hero_india_wonders",
        name: "Wonders of India",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["india", "wonders", "taj mahal", "heritage", "destination"],
        defaultText: {
            headline: "Wonders of India",
            subheadline: "Explore the Incredible",
        },
    },
    {
        id: "hero_asia_discover",
        name: "Discover Asia",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["asia", "discover", "southeast asia", "bali", "thailand"],
        defaultText: {
            headline: "Discover Asia",
            subheadline: "Exotic Adventures Await",
        },
    },
    {
        id: "hero_europe_dream",
        name: "Dream Europe",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["europe", "paris", "dream", "tour", "premium"],
        defaultText: {
            headline: "Dream Europe",
            subheadline: "The Trip of a Lifetime",
        },
    },

    // ─── INFO SPLIT (real poster format) ────────────────────────────────────────
    {
        id: "info_visa_split",
        name: "Get Your Visa Now",
        category: "Informational",
        layout: "InfoSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["visa", "apply", "now", "documentation", "international"],
        defaultText: {
            headline: "Get Your Visa Now",
            subheadline: "Fast • Reliable • Affordable",
        },
    },
    {
        id: "info_group_booking",
        name: "Group Booking Offer",
        category: "Promotion",
        layout: "InfoSplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["group", "booking", "offer", "corporate", "discount"],
        defaultText: {
            headline: "Group Booking Offer",
            subheadline: "Book 10+ Get Special Rates",
        },
    },
    {
        id: "info_holiday_split",
        name: "Holiday Deal Split",
        category: "Package Type",
        layout: "InfoSplitLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["holiday", "deal", "package", "split", "offer"],
        defaultText: {
            headline: "Holiday Deal",
            subheadline: "Fly, Stay & Tour — All Included",
        },
    },
    // ─── GRADIENT HERO (premium cinematic layout) ───────────────────────────────
    {
        id: "gradient_hero_maldives",
        name: "Maldives Cinematic",
        category: "Destination",
        subcategory: "Maldives",
        layout: "GradientHeroLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["maldives", "cinematic", "premium", "gradient", "luxury"],
    },
    {
        id: "gradient_hero_dubai",
        name: "Dubai Nightscape",
        category: "Destination",
        subcategory: "Dubai",
        layout: "GradientHeroLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["dubai", "cinematic", "skyline", "nightscape", "luxury"],
    },
    {
        id: "gradient_hero_flash",
        name: "Cinematic Flash Sale",
        category: "Promotion",
        subcategory: "Flash Sale",
        layout: "GradientHeroLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["flash sale", "cinematic", "urgent", "promotion"],
    },

    // ─── DIAGONAL SPLIT (modern dynamic layout) ──────────────────────────────────
    {
        id: "diagonal_bali",
        name: "Bali Diagonal",
        category: "Destination",
        subcategory: "Bali",
        layout: "DiagonalSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["bali", "diagonal", "modern", "dynamic", "tropical"],
    },
    {
        id: "diagonal_honeymoon",
        name: "Honeymoon Diagonal",
        category: "Package Type",
        subcategory: "Honeymoon",
        layout: "DiagonalSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["honeymoon", "romantic", "diagonal", "couples"],
    },
    {
        id: "diagonal_adventure",
        name: "Adventure Split",
        category: "Package Type",
        subcategory: "Adventure",
        layout: "DiagonalSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["adventure", "diagonal", "trek", "mountains", "dynamic"],
    },

    // ─── MAGAZINE COVER (elegant editorial layout) ────────────────────────────────
    {
        id: "magazine_paris",
        name: "Paris Editorial",
        category: "Destination",
        subcategory: "Europe",
        layout: "MagazineCoverLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["paris", "magazine", "editorial", "elegant", "europe"],
    },
    {
        id: "magazine_kashmir",
        name: "Kashmir Magazine",
        category: "Destination",
        subcategory: "Kashmir",
        layout: "MagazineCoverLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["kashmir", "magazine", "editorial", "valley", "snow"],
    },
    {
        id: "magazine_early_bird",
        name: "Early Bird Editorial",
        category: "Promotion",
        subcategory: "Early Bird",
        layout: "MagazineCoverLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["early bird", "editorial", "elegant", "promotion"],
    },

    // ─── DUOTONE (bold modern color filter) ───────────────────────────────────────
    {
        id: "duotone_thailand",
        name: "Thailand Duotone",
        category: "Destination",
        subcategory: "Thailand",
        layout: "DuotoneLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["thailand", "duotone", "modern", "bold", "asia"],
    },
    {
        id: "duotone_summer",
        name: "Summer Duotone",
        category: "Season",
        subcategory: "Summer",
        layout: "DuotoneLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["summer", "duotone", "vibrant", "modern", "beach"],
    },
    {
        id: "duotone_diwali",
        name: "Diwali Duotone",
        category: "Festival",
        subcategory: "Diwali",
        layout: "DuotoneLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["diwali", "duotone", "festival", "modern"],
        seasonalAvailability: ["diwali_2026"],
    },

    // ─── BOLD TYPOGRAPHY (oversized type layout) ──────────────────────────────────
    {
        id: "bold_type_goa",
        name: "Goa Bold Type",
        category: "Destination",
        subcategory: "Goa",
        layout: "BoldTypographyLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["goa", "bold", "typography", "minimal", "clean"],
    },
    {
        id: "bold_type_group",
        name: "Group Booking Bold",
        category: "Promotion",
        subcategory: "Group",
        layout: "BoldTypographyLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["group", "bold", "typography", "promotion", "booking"],
    },
    {
        id: "bold_type_corporate",
        name: "Corporate Bold",
        category: "Package Type",
        subcategory: "Corporate",
        layout: "BoldTypographyLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["corporate", "bold", "typography", "business", "professional"],
    },
];

export function getTemplatesByCategory(category: string) {
    return templates.filter(t => t.category === category);
}

export function searchTemplates(query: string) {
    const q = query.toLowerCase();
    return templates.filter(t =>
        t.name.toLowerCase().includes(q) ||
        t.category.toLowerCase().includes(q) ||
        (t.subcategory?.toLowerCase().includes(q)) ||
        t.tags.some(tag => tag.toLowerCase().includes(q))
    );
}

export function getTemplateById(id: string) {
    return templates.find(t => t.id === id);
}

export function getTemplatesByTier(tier: string) {
    if (tier === 'Enterprise') return templates;
    if (tier === 'Business') return templates.filter(t => t.tier !== 'Enterprise');
    if (tier === 'Pro') return templates.filter(t => t.tier === 'Starter' || t.tier === 'Pro');
    return templates.filter(t => t.tier === 'Starter');
}

export const TIER_ORDER: Record<string, number> = {
    Starter: 0,
    Pro: 1,
    Business: 2,
    Enterprise: 3,
};

/** Returns true if `userTier` can access `templateTier` */
export function canAccessTemplate(templateTier: string, userTier: string = 'Starter'): boolean {
    return (TIER_ORDER[userTier] ?? 0) >= (TIER_ORDER[templateTier] ?? 0);
}
