import { SocialTemplate } from './types';

/** Season templates — Summer, Monsoon, Winter */
export const seasonTemplates: SocialTemplate[] = [
    {
        id: "summer_beach_1",
        name: "Summer Beach Escape",
        category: "Season",
        subcategory: "Summer",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["summer", "beach", "escape", "hot"],
        palette: {
            bg: "bg-gradient-to-br from-cyan-400 to-blue-500",
            text: "text-white",
            accent: "#06b6d4",
            overlay: "linear-gradient(135deg, rgba(6,182,212,0.15), rgba(59,130,246,0.1))",
        },
    },
    {
        id: "summer_special_2",
        name: "Hot Summer Deals",
        category: "Season",
        subcategory: "Summer",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["summer", "deal", "sale", "vacation"],
        palette: {
            bg: "bg-gradient-to-br from-cyan-400 to-blue-500",
            text: "text-white",
            accent: "#06b6d4",
            overlay: "linear-gradient(135deg, rgba(6,182,212,0.15), rgba(59,130,246,0.1))",
        },
    },
    {
        id: "monsoon_magic_1",
        name: "Monsoon Magic",
        category: "Season",
        subcategory: "Monsoon",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["monsoon", "rain", "kerala", "nature"],
        palette: {
            bg: "bg-gradient-to-br from-slate-700 to-emerald-800",
            text: "text-white",
            accent: "#10b981",
            overlay: "linear-gradient(135deg, rgba(16,185,129,0.15), rgba(51,65,85,0.1))",
        },
    },
    {
        id: "winter_hills_1",
        name: "Winter Hills Special",
        category: "Season",
        subcategory: "Winter",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["winter", "snow", "manali", "hills"],
        palette: {
            bg: "bg-gradient-to-br from-indigo-400 to-blue-800",
            text: "text-white",
            accent: "#818cf8",
            overlay: "linear-gradient(135deg, rgba(129,140,248,0.15), rgba(30,64,175,0.1))",
        },
    },
    // Duotone Summer
    {
        id: "duotone_summer",
        name: "Summer Duotone",
        category: "Season",
        subcategory: "Summer",
        layout: "DuotoneLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["summer", "duotone", "vibrant", "modern", "beach"],
    },
    // Multi-image Season
    {
        id: "multi-summer-gallery-sq",
        name: "Summer Gallery",
        category: "Season",
        layout: "CollageGridLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["summer", "beach", "vacation", "sunny", "multi-image", "collage"],
        isMultiImage: true,
        imageSlotCount: 4,
        defaultText: {
            destination: "Summer Escapes",
            price: "\u20B934,999",
            offer: "Hot Summer Deals",
        },
        palette: {
            bg: "linear-gradient(135deg, #ca8a04, #f97316)",
            text: "text-white",
            accent: "#eab308",
            overlay: "linear-gradient(to top, rgba(113,63,18,0.95) 0%, rgba(113,63,18,0.4) 50%, transparent 100%)",
        },
    },
    {
        id: "multi-winter-destinations-sq",
        name: "Winter Destinations",
        category: "Season",
        layout: "TriPanelLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["winter", "snow", "hills", "cold", "multi-image", "triptych"],
        isMultiImage: true,
        imageSlotCount: 3,
        defaultText: {
            destination: "Winter Wonderlands",
            price: "\u20B944,999",
            offer: "Snowy Getaway",
        },
        palette: {
            bg: "linear-gradient(135deg, #1e40af, #475569)",
            text: "text-white",
            accent: "#38bdf8",
            overlay: "linear-gradient(to top, rgba(30,58,138,0.95) 0%, rgba(30,58,138,0.4) 50%, transparent 100%)",
        },
    },
    // Banner Ribbon — Summer
    {
        id: "banner_summer_deals",
        name: "Summer Deals Banner",
        category: "Season",
        subcategory: "Summer",
        layout: "BannerRibbonLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["summer", "deals", "banner", "premium", "sale", "offer", "discount"],
        isMultiImage: true,
        imageSlotCount: 2,
        palette: {
            bg: "bg-gradient-to-r from-blue-600 to-emerald-500",
            text: "text-white",
            accent: "#10b981",
            overlay: "",
        },
    },
];
