import { SocialTemplate } from './types';

/** Destination templates — core single-image layouts (standard, hero, gradient, diagonal, magazine, duotone, bold) */
export const destinationTemplates: SocialTemplate[] = [
    // ─── CORE DESTINATIONS ─────────────────────────────────────────────────────
    {
        id: "destination_dubai_1",
        name: "Dubai Skyline",
        category: "Destination",
        subcategory: "Dubai",
        layout: "BottomLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["dubai", "uae", "luxury", "burj"],
        palette: {
            bg: "bg-gradient-to-br from-amber-600 to-yellow-800",
            text: "text-white",
            accent: "#d4a017",
            overlay: "linear-gradient(135deg, rgba(212,160,23,0.15), rgba(161,98,7,0.1))",
        },
    },
    {
        id: "destination_bali_1",
        name: "Bali Paradise",
        category: "Destination",
        subcategory: "Bali",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["bali", "indonesia", "paradise", "tropical"],
        palette: {
            bg: "bg-gradient-to-br from-emerald-500 to-teal-600",
            text: "text-white",
            accent: "#10b981",
            overlay: "linear-gradient(135deg, rgba(16,185,129,0.15), rgba(13,148,136,0.1))",
        },
    },
    {
        id: "destination_maldives_1",
        name: "Maldives Luxury",
        category: "Destination",
        subcategory: "Maldives",
        layout: "ElegantLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["maldives", "luxury", "overwater", "island"],
        palette: {
            bg: "bg-gradient-to-br from-cyan-400 to-blue-600",
            text: "text-white",
            accent: "#06b6d4",
            overlay: "linear-gradient(135deg, rgba(6,182,212,0.15), rgba(37,99,235,0.1))",
        },
    },
    {
        id: "destination_kashmir_1",
        name: "Kashmir Valley",
        category: "Destination",
        subcategory: "Kashmir",
        layout: "SplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["kashmir", "valley", "snow", "paradise"],
        palette: {
            bg: "bg-gradient-to-br from-slate-600 to-blue-900",
            text: "text-white",
            accent: "#60a5fa",
            overlay: "linear-gradient(135deg, rgba(96,165,250,0.12), rgba(30,58,138,0.1))",
        },
    },
    {
        id: "destination_europe_1",
        name: "Europe Explorer",
        category: "Destination",
        subcategory: "Europe",
        layout: "BottomLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["europe", "paris", "rome", "travel"],
        palette: {
            bg: "bg-gradient-to-br from-blue-500 to-indigo-700",
            text: "text-white",
            accent: "#3b82f6",
            overlay: "linear-gradient(135deg, rgba(59,130,246,0.15), rgba(67,56,202,0.1))",
        },
    },
    {
        id: "destination_thailand_1",
        name: "Thailand Adventure",
        category: "Destination",
        subcategory: "Thailand",
        layout: "CenterLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["thailand", "bangkok", "phuket", "asia"],
        palette: {
            bg: "bg-gradient-to-br from-amber-500 to-orange-600",
            text: "text-white",
            accent: "#f59e0b",
            overlay: "linear-gradient(135deg, rgba(245,158,11,0.12), rgba(234,88,12,0.08))",
        },
    },
    {
        id: "destination_kerala_1",
        name: "God's Own Country",
        category: "Destination",
        subcategory: "Kerala",
        layout: "ElegantLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["kerala", "backwaters", "ayurveda", "india"],
        palette: {
            bg: "bg-gradient-to-br from-green-500 to-emerald-700",
            text: "text-white",
            accent: "#22c55e",
            overlay: "linear-gradient(135deg, rgba(34,197,94,0.15), rgba(4,120,87,0.1))",
        },
    },

    // ─── HERO SERVICES ─────────────────────────────────────────────────────────
    {
        id: "hero_india_wonders",
        name: "Wonders of India",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["india", "wonders", "taj mahal", "heritage", "destination"],
        defaultText: {
            headline: "Wonders of India",
            subheadline: "Explore the Incredible",
        },
    },
    {
        id: "hero_asia_discover",
        name: "Discover Asia",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["asia", "discover", "southeast asia", "bali", "thailand"],
        defaultText: {
            headline: "Discover Asia",
            subheadline: "Exotic Adventures Await",
        },
    },
    {
        id: "hero_europe_dream",
        name: "Dream Europe",
        category: "Destination",
        layout: "HeroServicesLayout",
        tier: "Pro",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "brand",
        tags: ["europe", "paris", "dream", "tour", "premium"],
        defaultText: {
            headline: "Dream Europe",
            subheadline: "The Trip of a Lifetime",
        },
    },

    // ─── GRADIENT HERO ─────────────────────────────────────────────────────────
    {
        id: "gradient_hero_maldives",
        name: "Maldives Cinematic",
        category: "Destination",
        subcategory: "Maldives",
        layout: "GradientHeroLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["maldives", "cinematic", "premium", "gradient", "luxury"],
    },
    {
        id: "gradient_hero_dubai",
        name: "Dubai Nightscape",
        category: "Destination",
        subcategory: "Dubai",
        layout: "GradientHeroLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["dubai", "cinematic", "skyline", "nightscape", "luxury"],
    },

    // ─── DIAGONAL SPLIT ────────────────────────────────────────────────────────
    {
        id: "diagonal_bali",
        name: "Bali Diagonal",
        category: "Destination",
        subcategory: "Bali",
        layout: "DiagonalSplitLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["bali", "diagonal", "modern", "dynamic", "tropical"],
    },

    // ─── MAGAZINE COVER ────────────────────────────────────────────────────────
    {
        id: "magazine_paris",
        name: "Paris Editorial",
        category: "Destination",
        subcategory: "Europe",
        layout: "MagazineCoverLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["paris", "magazine", "editorial", "elegant", "europe"],
    },
    {
        id: "magazine_kashmir",
        name: "Kashmir Magazine",
        category: "Destination",
        subcategory: "Kashmir",
        layout: "MagazineCoverLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["kashmir", "magazine", "editorial", "valley", "snow"],
    },

    // ─── DUOTONE ───────────────────────────────────────────────────────────────
    {
        id: "duotone_thailand",
        name: "Thailand Duotone",
        category: "Destination",
        subcategory: "Thailand",
        layout: "DuotoneLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "dark",
        tags: ["thailand", "duotone", "modern", "bold", "asia"],
    },

    // ─── BOLD TYPOGRAPHY ───────────────────────────────────────────────────────
    {
        id: "bold_type_goa",
        name: "Goa Bold Type",
        category: "Destination",
        subcategory: "Goa",
        layout: "BoldTypographyLayout",
        tier: "Starter",
        dimensions: { width: 1080, height: 1080 },
        aspectRatio: "square",
        colorScheme: "light",
        tags: ["goa", "bold", "typography", "minimal", "clean"],
    },
];
