export const ADD_ON_SELECT = [
  "category",
  "created_at",
  "description",
  "duration",
  "id",
  "image_url",
  "is_active",
  "name",
  "organization_id",
  "price",
  "updated_at",
].join(", ");

export const PROPOSAL_ADD_ON_SELECT = [
  "add_on_id",
  "category",
  "description",
  "id",
  "image_url",
  "is_selected",
  "name",
  "proposal_id",
  "quantity",
  "unit_price",
].join(", ");

export const CRM_CONTACT_SELECT = [
  "assigned_to",
  "budget_tier",
  "closed_at",
  "converted_at",
  "converted_profile_id",
  "created_at",
  "created_by",
  "departure_month",
  "destination",
  "duration_days",
  "email",
  "expected_value",
  "full_name",
  "id",
  "last_activity_at",
  "lost_reason",
  "notes",
  "organization_id",
  "phone",
  "phone_normalized",
  "source",
  "stage",
  "travelers",
  "updated_at",
].join(", ");

export const MONTHLY_OVERHEAD_EXPENSE_SELECT = [
  "amount",
  "category",
  "created_at",
  "created_by",
  "currency",
  "description",
  "id",
  "month_start",
  "organization_id",
  "updated_at",
].join(", ");

export const TRIP_SERVICE_COST_SELECT = [
  "category",
  "commission_amount",
  "commission_pct",
  "cost_amount",
  "created_at",
  "created_by",
  "currency",
  "description",
  "id",
  "notes",
  "organization_id",
  "pax_count",
  "price_amount",
  "trip_id",
  "updated_at",
  "vendor_name",
].join(", ");
