export const ITINERARY_SELECT = [
  "budget",
  "client_id",
  "created_at",
  "destination",
  "duration_days",
  "id",
  "interests",
  "raw_data",
  "summary",
  "template_id",
  "trip_title",
  "updated_at",
  "user_id",
].join(", ");

export const TRIP_SELECT = [
  "client_id",
  "created_at",
  "destination",
  "driver_id",
  "end_date",
  "gst_pct",
  "id",
  "itinerary_id",
  "name",
  "notes",
  "organization_id",
  "pax_count",
  "start_date",
  "status",
  "tcs_pct",
  "updated_at",
].join(", ");

export const EXTERNAL_DRIVER_SELECT = [
  "created_at",
  "full_name",
  "id",
  "is_active",
  "languages",
  "notes",
  "organization_id",
  "phone",
  "photo_url",
  "updated_at",
  "vehicle_capacity",
  "vehicle_plate",
  "vehicle_type",
].join(", ");
