export const MARKETPLACE_PROFILE_SELECT = [
  "boost_score",
  "compliance_documents",
  "created_at",
  "description",
  "featured_until",
  "gallery_urls",
  "id",
  "is_featured",
  "is_verified",
  "listing_quality_score",
  "listing_tier",
  "margin_rate",
  "organization_id",
  "rate_card",
  "search_vector",
  "service_regions",
  "specialties",
  "updated_at",
  "verification_level",
  "verification_notes",
  "verification_status",
  "verified_at",
].join(", ");
