import { NextRequest, NextResponse } from "next/server";
import { createClient as createServerClient } from "@/lib/supabase/server";
import { apiError } from "@/lib/api/response";
import { populateItineraryImages } from "@/lib/image-search";
import { logError } from "@/lib/observability/logger";

export async function POST(request: NextRequest) {
  try {
    const supabase = await createServerClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return apiError("Unauthorized", 401);
    }

    const body = await request.json().catch(() => null);
    const itinerary = body?.itinerary;
    const refreshAutoGenerated = body?.refreshAutoGenerated === true;

    if (!itinerary || !Array.isArray(itinerary.days)) {
      return apiError("Invalid itinerary payload", 400);
    }

    const enriched = await populateItineraryImages(itinerary, { refreshAutoGenerated });
    return NextResponse.json({ itinerary: enriched });
  } catch (error) {
    logError("[/api/itinerary/images:POST] Failed to enrich itinerary images", error);
    return apiError("Failed to enrich itinerary images", 500);
  }
}
