import { describe, expect, it } from "vitest";

import {
  buildImageSearchQueries,
  isAutoGeneratedImageUrl,
} from "../../../src/lib/image-search";

describe("image search query builder", () => {
  it("strips brochure noise and prioritizes landmark queries", () => {
    const queries = buildImageSearchQueries({
      title:
        "Phuket - James Bond Island by Speed Boat with Local Lunch + Sea Canoe (Excluding National Park Fee THB 300 Per Person Compulsory to pay Cash on Tour)",
      destination: "Phuket, Thailand",
    });

    expect(queries[0]).toBe("James Bond Island Phuket, Thailand");
    expect(queries).toContain("James Bond Island");
    expect(queries).toContain("Phuket, Thailand");
    expect(queries.join(" ")).not.toMatch(/speed boat|cash on tour|national park fee/i);
  });

  it("prefers explicit activity location when it is more precise than the destination", () => {
    const queries = buildImageSearchQueries({
      title: "Island hopping and snorkeling",
      location: "Maya Bay",
      destination: "Phuket, Thailand",
    });

    expect(queries[0]).toBe("Maya Bay Phuket, Thailand");
    expect(queries).toContain("Maya Bay");
  });

  it("recognizes auto-generated image URLs for safe refresh", () => {
    expect(isAutoGeneratedImageUrl("/unsplash-img/photo-1507525428034-b723cf961d3e")).toBe(true);
    expect(isAutoGeneratedImageUrl("https://upload.wikimedia.org/example.jpg")).toBe(true);
    expect(isAutoGeneratedImageUrl("https://cdn.example.com/manual-hotel-shot.jpg")).toBe(false);
  });
});
