import { describe, expect, it } from "vitest";

import {
  buildImageSearchQueries,
  getContextualFallback,
  isAutoGeneratedImageUrl,
} from "../../../src/lib/image-search";

describe("image search query builder", () => {
  it("strips brochure noise and prioritizes landmark queries", () => {
    const queries = buildImageSearchQueries({
      title:
        "Phuket - James Bond Island by Speed Boat with Local Lunch + Sea Canoe (Excluding National Park Fee THB 300 Per Person Compulsory to pay Cash on Tour)",
      destination: "Phuket, Thailand",
    });

    expect(queries[0]).toBe("James Bond Island Phuket, Thailand");
    expect(queries).toContain("James Bond Island");
    expect(queries).toContain("Phuket, Thailand");
    expect(queries.join(" ")).not.toMatch(/speed boat|cash on tour|national park fee/i);
  });

  it("prefers explicit activity location when it is more precise than the destination", () => {
    const queries = buildImageSearchQueries({
      title: "Island hopping and snorkeling",
      location: "Maya Bay",
      destination: "Phuket, Thailand",
    });

    expect(queries[0]).toBe("Maya Bay Phuket, Thailand");
    expect(queries).toContain("Maya Bay");
  });

  it("extracts route endpoints from transfer-style titles before falling back", () => {
    const queries = buildImageSearchQueries({
      title: "Phuket Airport HKT to Krabi Hotel - One Way Private Transfer",
      destination: "Krabi, Thailand",
    });

    expect(queries[0]).toMatch(/Krabi Krabi, Thailand|Phuket Airport Krabi, Thailand/);
    expect(queries).toContain("Phuket Airport Krabi, Thailand");
    expect(queries.join(" ")).not.toMatch(/one way|private transfer|hotel|hkt/i);
  });

  it("recognizes auto-generated image URLs for safe refresh", () => {
    expect(isAutoGeneratedImageUrl("/unsplash-img/photo-1507525428034-b723cf961d3e")).toBe(true);
    expect(isAutoGeneratedImageUrl("https://upload.wikimedia.org/example.jpg")).toBe(true);
    expect(isAutoGeneratedImageUrl("https://cdn.example.com/manual-hotel-shot.jpg")).toBe(false);
  });

  it("uses destination-aware tropical fallbacks for thailand island content", () => {
    const fallback = getContextualFallback(
      "Krabi - 7 Island Sunset Tour by Long Tail Boat + Dinner Phuket Thailand",
    );

    expect(fallback).toBeTruthy();
    expect(fallback).toMatch(
      /photo-(1507525428034-b723cf961d3e|1496417263034-38ec4f0b665a|1506929562872-bb421503ef21|1530789253388-582c481c54b0|1544735716-392fe2489ffa|1510798831971-661eb04b3739)/,
    );
  });
});
