import { afterEach, describe, expect, it, vi } from "vitest";

import {
  buildImageSearchQueries,
  getContextualFallback,
  isAutoGeneratedImageUrl,
  populateItineraryImages,
  shouldPreferContextualFallback,
} from "../../../src/lib/image-search";

describe("image search query builder", () => {
  it("strips brochure noise and prioritizes landmark queries", () => {
    const queries = buildImageSearchQueries({
      title:
        "Phuket - James Bond Island by Speed Boat with Local Lunch + Sea Canoe (Excluding National Park Fee THB 300 Per Person Compulsory to pay Cash on Tour)",
      destination: "Phuket, Thailand",
    });

    expect(queries[0]).toBe("James Bond Island Phuket, Thailand");
    expect(queries).toContain("James Bond Island");
    expect(queries).toContain("Phuket, Thailand");
    expect(queries.join(" ")).not.toMatch(/speed boat|cash on tour|national park fee/i);
  });

  it("prefers explicit activity location when it is more precise than the destination", () => {
    const queries = buildImageSearchQueries({
      title: "Island hopping and snorkeling",
      location: "Maya Bay",
      destination: "Phuket, Thailand",
    });

    expect(queries[0]).toBe("Maya Bay Phuket, Thailand");
    expect(queries).toContain("Maya Bay");
  });

  it("extracts route endpoints from transfer-style titles before falling back", () => {
    const queries = buildImageSearchQueries({
      title: "Phuket Airport HKT to Krabi Hotel - One Way Private Transfer",
      destination: "Krabi, Thailand",
    });

    expect(queries[0]).toMatch(/Krabi Thailand|Phuket Airport Thailand/);
    expect(queries).toContain("Phuket Airport Thailand");
    expect(queries.join(" ")).not.toMatch(/one way|private transfer|hotel|hkt/i);
  });

  it("does not mash the trip destination into a different activity location", () => {
    const queries = buildImageSearchQueries({
      title: "Krabi - 7 Island Sunset Tour by Long Tail Boat + Dinner",
      location: "Krabi",
      destination: "Phuket, Thailand",
    });

    expect(queries[0]).toBe("Krabi Thailand");
    expect(queries).not.toContain("Krabi Phuket, Thailand");
  });

  it("recognizes auto-generated image URLs for safe refresh", () => {
    expect(isAutoGeneratedImageUrl("/unsplash-img/photo-1507525428034-b723cf961d3e")).toBe(true);
    expect(isAutoGeneratedImageUrl("https://upload.wikimedia.org/example.jpg")).toBe(true);
    expect(isAutoGeneratedImageUrl("https://cdn.example.com/manual-hotel-shot.jpg")).toBe(false);
  });

  it("uses destination-aware tropical fallbacks for thailand island content", () => {
    const fallback = getContextualFallback(
      "Krabi - 7 Island Sunset Tour by Long Tail Boat + Dinner Phuket Thailand",
    );

    expect(fallback).toBeTruthy();
    expect(fallback).toMatch(
      /photo-(1507525428034-b723cf961d3e|1496417263034-38ec4f0b665a|1506929562872-bb421503ef21|1530789253388-582c481c54b0|1544735716-392fe2489ffa|1510798831971-661eb04b3739)/,
    );
  });

  it("prefers contextual fallbacks first for transfer and show entries", () => {
    expect(
      shouldPreferContextualFallback(
        "Krabi Hotel to Phuket Hotel En-Route city tour + Dolphin Show - One Way Private Transfer",
      ),
    ).toBe(true);

    const fallback = getContextualFallback(
      "Krabi Hotel to Phuket Hotel En-Route city tour + Dolphin Show Phuket Thailand",
    );

    expect(fallback).toBeTruthy();
    expect(fallback).toMatch(/\/unsplash-img\/photo-/);
    expect(fallback).not.toMatch(/1469854523086-cc02fe5d8800/);
  });
});

describe("populate itinerary images", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
  });

  it("resolves exact landmark images via Wikidata/Wikimedia first", async () => {
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);

      if (url.includes("wbsearchentities") && decodeURIComponent(url).includes("Kapalee")) {
        return {
          ok: true,
          json: async () => ({
            search: [
              {
                id: "Q6363343",
                label: "Kapaleeshwarar Temple",
                description: "Hindu temple in Chennai, India",
              },
            ],
          }),
        };
      }

      if (url.includes("wbsearchentities")) {
        return {
          ok: true,
          json: async () => ({ search: [] }),
        };
      }

      if (url.includes("wbgetentities") && url.includes("Q6363343")) {
        return {
          ok: true,
          json: async () => ({
            entities: {
              Q6363343: {
                claims: {
                  P18: [
                    {
                      mainsnak: {
                        datavalue: {
                          value: "Kapaleeshwarar_Temple_Chennai.jpg",
                        },
                      },
                    },
                  ],
                },
                sitelinks: {
                  enwiki: {
                    title: "Kapaleeshwarar Temple",
                  },
                },
              },
            },
          }),
        };
      }

      throw new Error(`Unexpected fetch: ${url}`);
    });

    vi.stubGlobal("fetch", fetchMock);

    const enriched = await populateItineraryImages({
      destination: "Chennai, India",
      days: [
        {
          activities: [
            {
              title: "Kapaleeswarar Temple",
              location: "Mylapore, Chennai",
            },
          ],
        },
      ],
    });

    const activity = enriched.days[0].activities[0];
    expect(activity.image).toContain("Kapaleeshwarar_Temple_Chennai.jpg");
    expect(activity.image_source).toBe("wikimedia-entity");
    expect(activity.image_confidence).toBe("high");
    expect(activity.image_entity_id).toBe("Q6363343");
    expect(activity.image_query).toMatch(/Kapaleeswarar Temple/);
  });

  it("does not overwrite higher-confidence auto-generated images during refresh", async () => {
    const fetchMock = vi.fn();
    vi.stubGlobal("fetch", fetchMock);

    const enriched = await populateItineraryImages(
      {
        destination: "Chennai, India",
        days: [
          {
            activities: [
              {
                title: "San Thome Basilica",
                image: "https://commons.wikimedia.org/wiki/Special:FilePath/San_Thome_Basilica.jpg?width=1200",
                imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/San_Thome_Basilica.jpg?width=1200",
                image_source: "wikimedia-entity",
                image_confidence: "high",
                image_query: "San Thome Basilica Chennai",
                image_entity_id: "Q7410925",
              },
            ],
          },
        ],
      },
      { refreshAutoGenerated: true },
    );

    const activity = enriched.days[0].activities[0];
    expect(activity.image_source).toBe("wikimedia-entity");
    expect(activity.image_confidence).toBe("high");
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it("avoids reusing the same auto-generated image across multiple activities", async () => {
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);

      if (url.includes("wbsearchentities")) {
        return {
          ok: true,
          json: async () => ({ search: [] }),
        };
      }

      if (url.includes("api.pexels.com")) {
        return {
          ok: true,
          json: async () => ({
            photos: [
              { src: { large: "https://images.example.com/repeated.jpg" } },
            ],
          }),
        };
      }

      if (url.includes("pixabay.com/api/")) {
        return {
          ok: true,
          json: async () => ({
            hits: [
              { webformatURL: "https://images.example.com/repeated.jpg" },
            ],
          }),
        };
      }

      if (url.includes("en.wikipedia.org")) {
        return {
          ok: true,
          json: async () => ({ query: { pages: {} } }),
        };
      }

      throw new Error(`Unexpected fetch: ${url}`);
    });

    vi.stubGlobal("fetch", fetchMock);

    const enriched = await populateItineraryImages(
      {
        destination: "Ubud, Bali, Indonesia",
        days: [
          {
            activities: [
              { title: "Ubud Monkey Forest", location: "Ubud, Gianyar Regency" },
              { title: "Ubud Royal Palace", location: "Ubud, Gianyar Regency" },
              { title: "Campuhan Ridge Walk", location: "Ubud, Gianyar Regency" },
            ],
          },
        ],
      },
      { refreshAutoGenerated: true },
    );

    const images = enriched.days[0].activities.map((activity) => activity.image);
    expect(new Set(images).size).toBe(images.length);
  });
});
